import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
for (const file of ["package.json","language-configuration.json","syntaxes/proofscript.tmLanguage.json"]) JSON.parse(fs.readFileSync(path.join(root,file),"utf8"));
for (const file of ["src/extension.js","README.md","media/proofscript-view.svg","server/run-lsp.mjs"]) if (!fs.existsSync(path.join(root,file))) throw new Error("missing " + file);
const syntax = spawnSync(process.execPath, ["--check", path.join(root,"src/extension.js")], { encoding:"utf8" });
if (syntax.status !== 0) throw new Error(syntax.stderr || syntax.stdout);
const pkg = JSON.parse(fs.readFileSync(path.join(root,"package.json"),"utf8"));
if (pkg.version !== "0.1.0-dev.0") throw new Error("unexpected editor version " + pkg.version);
const source = fs.readFileSync(path.join(root,"src/extension.js"),"utf8");
for (const needle of ["EXPECTED_LSP_PROTOCOL_VERSION = 1","textDocument/hover","textDocument/documentSymbol","textDocument/completion","textDocument/definition","textDocument/references","textDocument/rename","textDocument/semanticTokens/full","proofscript/documentStatus","proofscript/semanticInfo","proofscript/serverInfo","proofscript/goals","$/cancelRequest","Ignoring stale diagnostics","registerWebviewViewProvider","registerDocumentSemanticTokensProvider","textDocument/formatting","registerDocumentFormattingEditProvider","textDocument/codeAction","registerCodeActionsProvider"]) if (!source.includes(needle)) throw new Error("missing active editor capability: " + needle);
for (const unsupported of ["textDocument/signatureHelp","proofscript/proofState"]) if (source.includes(unsupported)) throw new Error("active editor must not register unsupported method: " + unsupported);
console.log("PRODUCT_V1_VSCODE_SMOKE=PASS");
