import { ProofScriptError } from "../../core/errors.js";
import type { ProofScriptPlugin } from "../../core/plugin-api.js";
import type { EmitContext, IRProgram } from "../../core/model.js";
import { isPropSort, isPropositionType } from "../../core/type-utils.js";

function emitProgram(program: IRProgram, context: EmitContext): string {
  const lines = [
    "// Generated by ProofScript plugin MVP.",
    "// This backend uses num_bigint::BigUint as the Nat representation for the current subset; correspondence is not yet mechanically proved.",
    "use num_bigint::BigUint;",
    "",
  ];

  for (const declaration of program.declarations) {
    if (declaration.kind === "extension") {
      if (context.registry.getOperation(declaration.op).domain === "proof") continue;
      lines.push(context.emitDeclaration(declaration), "");
      continue;
    }
    if (declaration.kind === "mutual") {
      throw new ProofScriptError("PS3331", "Rust backend is not an active ProofScript v0.34 target and has no mutual-recursion correspondence mapping.");
    }
    const defaultParam = declaration.params.find((param) => param.defaultValue !== undefined);
    if (defaultParam) {
      throw new ProofScriptError("PS3329", `Rust backend does not yet publish a correspondence rule for default parameter '${defaultParam.name}'; default insertion remains Lean-facing in v0.10.`);
    }
    const typeParams = declaration.params.filter((param) => param.isTypeParam);
    const propositionParam = typeParams.find((param) => isPropSort(param.type));
    if (propositionParam) {
      throw new ProofScriptError("PS3215", `Rust backend does not lower proposition parameter '${propositionParam.name}' as a runtime generic; proposition/proof erasure requires an explicit correspondence rule.`);
    }
    const explicitTypeParam = typeParams.find((param) => param.binderInfo === "explicit");
    if (explicitTypeParam) {
      throw new ProofScriptError("PS3212", `Rust backend does not preserve explicit Type-valued binder '${explicitTypeParam.name}'; use an implicit type parameter for the portable generic slice.`);
    }
    const valueParams = declaration.params.filter((param) => !param.isTypeParam);
    const proofLikeParam = valueParams.find((param) => isPropositionType(param.type));
    if (proofLikeParam) {
      throw new ProofScriptError("PS3225", `Rust backend does not lower proof parameter '${proofLikeParam.name}' as runtime data.`);
    }
    if (isPropositionType(declaration.returnType)) {
      throw new ProofScriptError("PS3226", `Rust backend does not lower proposition-valued definitions as runtime values.`);
    }
    const implicitValue = valueParams.find((param) => param.binderInfo !== "explicit");
    if (implicitValue) {
      throw new ProofScriptError("PS3213", `Rust backend has no correspondence mapping yet for ${implicitValue.binderInfo} value binder '${implicitValue.name}'.`);
    }
    const generics = typeParams.length > 0 ? `<${typeParams.map((param) => param.name).join(", ")}>` : "";
    const params = valueParams.map((param) => `${param.name}: ${context.emitType(param.type)}`).join(", ");
    lines.push(`pub fn ${declaration.name}${generics}(${params}) -> ${context.emitType(declaration.returnType)} {`);
    lines.push(`    ${context.emitExpr(declaration.body)}`);
    lines.push("}", "");
  }

  return lines.join("\n");
}

const plugin: ProofScriptPlugin = {
  id: "proofscript.backend.rust",
  version: "0.91.0",
  kind: "backend",
  setup(registry) {
    registry.registerTarget({
      id: "rust",
      displayName: "Rust",
      capabilities: new Set(["core.nat", "core.nat.add", "core.generic", "lean.hAdd"]),
      emitProgram,
    });

    registry.registerTargetTypeLowering("rust", "Nat", () => "BigUint");
    registry.registerTargetTypeFamilyLowering("rust", "core.typevar", (type) => type.displayName);
    registry.registerTargetTypeFamilyLowering("rust", "core.pi", (type, context) => {
      if (!type.domain || !type.codomain || !type.binder) throw new ProofScriptError("PS3229", "Malformed Pi type in Rust lowering.");
      if (type.binder.name !== "_" || type.binder.binderInfo !== "explicit") {
        throw new ProofScriptError("PS3230", `Rust backend only lowers non-dependent explicit function arrows; '${type.displayName}' retains dependent/binder semantics.`);
      }
      return `fn(${context.emitType(type.domain)}) -> ${context.emitType(type.codomain)}`;
    });
    registry.registerTargetExprLowering("rust", "core.nat.literal", (expr) => {
      if (expr.kind !== "literal") throw new ProofScriptError("PS3203", "Expected Nat literal IR node.");
      return `BigUint::parse_bytes(b\"${expr.value}\", 10).expect(\"valid Nat literal\")`;
    });
    registry.registerTargetExprLowering("rust", "core.nat.add", (expr, context) => {
      if (expr.kind !== "op") throw new ProofScriptError("PS3204", "Expected Nat add IR node.");
      return `(${context.emitExpr(expr.args[0]!)} + ${context.emitExpr(expr.args[1]!)})`;
    });
    registry.registerTargetExprLowering("rust", "lean.hAdd", (expr, context) => {
      if (expr.kind !== "op" || expr.args.length !== 3 || expr.type.id !== "Nat" || expr.args[1]?.type.id !== "Nat" || expr.args[2]?.type.id !== "Nat") {
        throw new ProofScriptError("PS32AR2", "Rust v0.86 only preserves the historical Nat + correspondence for HAdd.");
      }
      return `(${context.emitExpr(expr.args[1]!)} + ${context.emitExpr(expr.args[2]!)})`;
    });
  },
};

export default plugin;
