export const PSC1_TRUST_LABEL = "trusted-boundary standalone small subset; not fully formally equivalent to Lean 4 yet";
export const PSC1_IMPLEMENTATION_PROFILE = "standalone-small-subset-no-lean4-p5.78-arena-tutorial-harness0";

export const PSC1_SUPPORTED_FEATURES = Object.freeze([
  "def with explicit result type",
  "const/function aliases normalized to checked def declarations, v0.6.1 match-with brace bodies, where bodies, expression-bodied structure literals/updates, and class-body projection fields",
  "Nat / Bool / Unit / Eq / Int / String / Option / List / Array / Except core prelude via checked bootstrap artifact",
  "Option(A), Option.none(A), Option.some(A, value), Option.isSome(A, value), Option.isNone(A, value), Option.getD(A, value, fallback), Option.orElse(A, value, fallback), Option.fold(A, B, none, some, value), Option.any(A, p, value), reference v0.6.1 expression-bodied declarations, braced if, match-with brace bodies, where bodies, and structure literal/update expression bodies, Option.toList(A, value), Option.toArray(A, value), Option.filter(A, p, value), Option.flatten(A, value), Option.map(A, B, f, value), Option.bind(A, B, value, f), and exhaustive Option matches over non-indexed checked recursors",
  "List(A), List.nil(A), List.cons(A, head, tail), List.map(A, B, f, xs), List.foldl(A, B, f, init, xs), and List.filter(A, p, xs), List.append(A, left, right), List.length(A, xs), List.range(count), List.replicate(A, count, value), List.singleton(A, value), List.toArray(A, xs), List.isEmpty(A, xs), List.head?(A, xs), List.get?(A, xs, index), List.last?(A, xs), List.tail?(A, xs), List.reverse(A, xs), List.any(A, p, xs), List.all(A, p, xs), and List.find?(A, p, xs), and List.take(A, xs, count), List.takeWhile(A, p, xs), List.dropWhile(A, p, xs), and List.drop(A, xs, count) over checked finite List payloads, exhaustive List(Nat) matches, and bounded structural recursion over List(Nat)",
  "Array(A), Array.mk(A, data), expected-type-directed Array(Nat) literals, Array.size(A, xs), Array.range(count), Array.replicate(A, count, value), Array.singleton(A, value), Array.toList(A, xs), Array.get?(A, xs, index), Array.head?(A, xs), Array.last?(A, xs), Array.tail?(A, xs), Array.map(A, B, f, xs), Array.foldl(A, B, f, init, xs), and Array.filter(A, p, xs), Array.append(A, left, right), Array.isEmpty(A, xs), Array.reverse(A, xs), Array.any(A, p, xs), Array.all(A, p, xs), and Array.find?(A, p, xs), and Array.take(A, xs, count), Array.takeWhile(A, p, xs), Array.dropWhile(A, p, xs), and Array.drop(A, xs, count) over checked Array.mk/List payloads before JS/TypeScript emission",
  "Except(E, A), Except.error(E, A, error), Except.ok(E, A, value), Except.isOk(E, A, value), Except.isError(E, A, value), Except.getD(E, A, value, fallback), Except.orElse(E, A, value, fallback), Except.toOption(E, A, value), Except.toError(E, A, value), Except.getErrorD(E, A, value, fallback), Except.swap(E, A, value), Except.fold(E, A, B, error, ok, value), Except.bimap(E, F, A, B, mapError, mapOk, value), Except.toList(E, A, value), Except.flatten(E, A, value), Except.map(E, A, B, f, value), Except.bind(E, A, B, value, f), exhaustive Except(String, Nat) matches, and JS/TypeScript tagged-record emission after Core checking",
  "String literals typed as checked Core `lit.str`, simple String definitions/functions, and JS/TypeScript string emission after Core checking",
  "Int literals typed as checked Core `lit.int`, simple Int definitions/functions, bounded Int.neg/Int.add/Int.sub/Int.beq on explicit literals, type-directed Int +, -, and == surface operators, and JS/TypeScript BigInt emission after Core checking",
  "Bool.not / Bool.xor execution through checked bootstrap declarations",
  "Nat literals and constructor-normalized Nat values",
  "curried Nat functions",
  "Nat.zero / Nat.succ / Nat.add / Nat.pred / Nat.sub / Nat.mul / Nat.beq / Nat.leb / Nat.ltb execution",
  "Lean-style Nat addition infix `x + y` lowered to checked Nat.add before JS/TypeScript emission",
  "Lean-style Nat subtraction infix `x - y` lowered to checked Nat.sub with saturating-at-zero Nat semantics",
  "Lean-style Nat multiplication infix `x * y` lowered to checked Nat.mul with higher precedence than + and -",
  "Lean-style Nat Boolean comparison infix `x == y`, `x <= y`, and `x < y` lowered to checked Nat.beq/Nat.leb/Nat.ltb before JS/TypeScript emission",
  "Lean-style whitespace function application such as `Nat.add x 2` and `f x` lowered to checked Core applications",
  "direct calls to checked earlier definitions",
  "kernel check + Core artifact emission before JS/TypeScript emission",
  "standalone TypeScript module emission via pslive build-ts after Core checking",
  "reserved JavaScript/TypeScript/internal runtime output identifiers are emitted through safe generated bindings while preserving original ProofScript export keys",
  "theorem/example by rfl and by { rfl } for definitional-equality Eq goals",
  "theorem/example by exact term and by { exact term } for already-checked proof terms",
  "theorem/example by { intro x; ... } for explicit function/forall goals",
  "theorem/example by { assumption } via local-context exact-type search",
  "theorem/example by { apply term; ... } for one explicit generated implication/function subgoal",
  "Boolean conditional expression bif (b) { then } else { else } via checked Bool.rec",
  "Lean-style Boolean if expression `if b then t else e` parsed as checked Bool.rec sugar",
  "Lean-style Boolean operators `a && b` and `a || b` lowered to checked Bool.rec sugar with && binding tighter than ||",
  "Lean-style Boolean prefix `!b` lowered to checked Bool.not before JS/TypeScript emission",
  "simple exhaustive match expressions over Bool lowered to checked recursor applications",
  "simple and multi-literal Nat/catch-all match expressions lowered to checked nested Nat.rec and executable JS",
  "Lean-style constructor pattern binders such as Nat.succ k in the PSC-1 match subset",
  "parameterless single-constructor structure values and projections emitted as frozen JS records after Core checking",
  "structure literal field punning such as {x, y} parsed as checked same-name field assignments",
  "single-constructor structure match/destructuring emitted as checked recursor applications over frozen JS records",
  "nonrecursive multi-constructor user inductive matches emitted as checked recursor applications over frozen tagged records",
  "simple self-recursive user inductive primitive recursion emitted as checked recursor applications with runtime-computed IHs",
  "expected-type-directed constructor shorthand such as red and some(7) elaborated to checked Color.red / MaybeNat.some applications",
  "expected-function-type partial constructor shorthand such as def mkSome: Nat -> MaybeNat := { some } elaborated to the checked constructor function",
  "dotted structure projection sugar x.field elaborated to generated checked projection applications",
  "structure update expressions, including field punning, bounded nested field-path updates, and parenthesized checked base expressions, lowered to checked constructor/projection applications and executable JS",
  "local let/have prefixes inside def-body blocks lowering to checked Core let terms",
  "canonical self-delimited by-block theorem/example declarations close at final } with no command semicolon",
  "reference-governed PSC-1 canonical where blocks for simple inductive/structure declarations plus v0.6.1 structure literal/update expression bodies and class body projection fields",
] as const);

export const PSC1_FAIL_CLOSED_FEATURES = Object.freeze([
  "proposition/Decidable if over Prop until Decidable/typeclass elaboration exists; PSC-1 currently supports direct Boolean if sugar only",
  "general tactic scripts beyond PSC-1 by { rfl } / by { exact term } / by { intro x; ... } / by { assumption } / by { apply term; ... }",
  "macros, full tactics, typeclass elaboration as source behavior",
  "JavaScript // source comments and arrow-only lambdas in standard PSC-1",
  "local function binder sugar and local recursion `let rec` in def-body blocks",
  "general recursion execution beyond Nat.rec and bounded simple self-recursive user-inductive recursors with direct owner-typed recursive fields",
  "general pattern matching beyond exhaustive non-indexed constructor cases with supported uniform parameters",
  "general algebraic-data runtime interop beyond the bounded PSC-1 frozen-record constructor/projection/recursor encoding with erased uniform parameters",
  "general Array APIs beyond expected-type-directed literals plus bounded size/range/replicate/singleton/toList/get?/head?/last?/tail?/take/takeWhile/dropWhile/drop/map/foldl/filter/append/isEmpty/reverse/any/all/find? over checked List payloads, broader List APIs beyond explicit constructors/match/structural recursion/List.map/List.foldl/List.filter/List.append/List.length/List.range/List.replicate/List.singleton/List.toArray/List.isEmpty/List.head?/List.get?/List.last?/List.tail?/List.reverse/List.any/List.all/List.find?/List.take/List.takeWhile/List.dropWhile/List.drop, broader Option/Except APIs beyond explicit constructors, isSome/isNone/isOk/isError predicates, getD default extraction helpers, orElse fallback helpers, Option/Except conversion helpers, explicit Option.filter/Option.flatten/Option.fold/Option.any/Except.mapError/Except.flatten/Except.toError/Except.getErrorD/Except.swap/Except.fold/Except.bimap, exhaustive matches, v0.6.1 structure literal/update expression-body parsing, and bounded map, Int ordering/conversion APIs, Int multiplication operator, full typeclass-overloaded numeric elaboration, String library/string pattern matching/Unicode APIs, and UInt/Float/runtime semantics",
  "IO, modules as runtime namespaces, effects",
  "full Lean compatibility or formal equivalence",
] as const);
