import assert from 'node:assert/strict'; import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path'; import {fileURLToPath} from 'node:url'; import {spawnSync} from 'node:child_process';
import {checkCoreDeclarations} from '@proofscript/kernel'; import {decodeArtifact} from '@proofscript/kernel-codec'; import {verifyFile} from '@proofscript/verifier'; import {checkUnifiedSource,UNIFIED_INTEGRATION_PROFILE} from '@proofscript/unified-bridge'; import {stripStandardBootstrap} from '@proofscript/environment'; import {emitLeanArtifact} from '@proofscript/lean-export';
import { assertCoreDeclarationsRejected, assertOnlyStandardBootstrapAssumptions, standardBootstrapAxiomSet } from "./bootstrap-assumptions.ts";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'); const source=fs.readFileSync(path.join(root,'integration-fixtures/production-p3/list.ps'),'utf8'); const checked=checkUnifiedSource(source);
assert.ok(['PRODUCTION-P3-practical-profile', 'PRODUCTION-P4-project-modules', 'PRODUCTION-P5-module-namespaces', 'PRODUCTION-P6-bounded-string'].includes(checked.integrationProfile)); assert.equal(checked.integrationProfile,UNIFIED_INTEGRATION_PROFILE); assert.equal(checked.kernelSummary.status,'accepted'); assertOnlyStandardBootstrapAssumptions(checked.kernelSummary.assumptions, "checked kernel summary");
const list=checked.coreArtifact.declarations.find(d=>d.kind==='inductive'&&d.name==='ProofScript.Core.P3.List'); assert.ok(list&&list.kind==='inductive'); assert.deepEqual(list.constructors.map(c=>c.name),['ProofScript.Core.P3.List.nil','ProofScript.Core.P3.List.cons']);
for(const n of ['listLength','listMap','listAppend','sample','mapped','appended','lenSample','lenMapped','lenAppended']) assert.ok(checked.coreArtifact.declarations.some(d=>d.name===n),`missing ${n}`);
assert.match(checked.typescript,/export function listLength<A>/); assert.match(checked.typescript,/export function listMap<A, B>/); assert.match(checked.typescript,/export function listAppend<A>/);
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ps-p3-list-')); try { const artifact=path.join(tmp,'list.pscore.json'); fs.writeFileSync(artifact,JSON.stringify(checked.coreArtifact,null,2)+'\n'); decodeArtifact(JSON.parse(fs.readFileSync(artifact,'utf8'))); const replay=verifyFile(artifact,standardBootstrapAxiomSet()); assert.equal(replay.status,'accepted'); assert.equal(replay.projectPluginsLoaded,false);
fs.writeFileSync(path.join(tmp,'list.ts'),checked.typescript+'\nconsole.log("S="+lenSample());\nconsole.log("M="+lenMapped());\nconsole.log("A="+lenAppended());\n'); fs.writeFileSync(path.join(tmp,'package.json'),'{"type":"module"}\n'); const tsc=spawnSync('tsc',['list.ts','--target','ES2022','--module','NodeNext','--moduleResolution','NodeNext','--skipLibCheck','--outDir','js'],{cwd:tmp,encoding:'utf8'}); assert.equal(tsc.status,0,tsc.stderr||tsc.stdout); const rt=spawnSync(process.execPath,[path.join(tmp,'js/list.js')],{encoding:'utf8'}); assert.equal(rt.status,0,rt.stderr||rt.stdout); assert.deepEqual(rt.stdout.trim().split(/\r?\n/),['S=3','M=3','A=6']);
const leanBin=process.env.PROOFSCRIPT_LEAN_BIN; if(leanBin){const v=spawnSync(leanBin,['--version'],{encoding:'utf8'});assert.equal(v.status,0,v.stderr||v.stdout);assert.match(v.stdout,/version 4\.33\.1,/);assert.match(v.stdout,/819816b2e0a3bf405af45ae5c7af2491d8f5bee6/);const decoded=decodeArtifact(JSON.parse(fs.readFileSync(artifact,'utf8')));const stripped=stripStandardBootstrap(decoded)??decoded;const lp=path.join(tmp,'list.lean');fs.writeFileSync(lp,`${emitLeanArtifact(stripped)}\n#reduce lenSample\n#reduce lenMapped\n#reduce lenAppended\n`);const lean=spawnSync(leanBin,[lp],{encoding:'utf8',env:{...process.env,TERM:'xterm'}});assert.equal(lean.status,0,lean.stderr||lean.stdout);const tail=lean.stdout.replace(/\x1b\[[0-9;]*[A-Za-z]/g,'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).slice(-3);assert.deepEqual(tail,['3','3','6']);}
const tampered=structuredClone(checked.coreArtifact);const bad=tampered.declarations.find(d=>d.kind==='inductive'&&d.name==='ProofScript.Core.P3.List');assert.ok(bad&&bad.kind==='inductive');const cons=bad.constructors.find(c=>c.name==='ProofScript.Core.P3.List.cons');assert.ok(cons&&cons.type.tag==='pi'&&cons.type.body.tag==='pi');cons.type.body.domain={tag:'const',name:'Bool',levels:[]};assertCoreDeclarationsRejected(checkCoreDeclarations(tampered.declarations,'KERNEL-level-instantiation-conformance1'), /type mismatch|expected|constructor|application/i);
} finally {fs.rmSync(tmp,{recursive:true,force:true});} console.log('✓ Production P3 List: checked canonical list + generic structural length/map/append + replay + exact Lean/TS + tamper rejection passed');
