import type { ProofScriptPlugin } from "../../core/plugin-api.js";

const plugin: ProofScriptPlugin = {
  id: "proofscript.backend-feature.typescript-to-string-io-error",
  version: "0.91.0",
  kind: "backend-feature",
  requires: [
    "proofscript.backend-feature.typescript-to-string",
    "proofscript.backend-feature.typescript-io-error-structured",
    "proofscript.feature.to-string-io-error",
  ],
  setup(registry) {
    registry.registerSemanticInfo("typescript.toStringIOErrorPrelude", [
      `const __psIOErrorDownCaseFirst = (s: string): string => {`,
      `  if (s.length === 0) return s;`,
      `  const c = s.charCodeAt(0);`,
      `  return c >= 65 && c <= 90 ? String.fromCharCode(c + 32) + s.slice(1) : s;`,
      `};`,
      `const __psIOErrorCodeString = (code: UInt32): string => BigInt(code).toString(10);`,
      `const __psIOErrorFopenToString = (gist: string, fn: string, code: UInt32, details: string | undefined): string =>`,
      `  details === undefined`,
      `    ? __psIOErrorDownCaseFirst(gist) + " (error code: " + __psIOErrorCodeString(code) + ")\\n  file: " + fn`,
      `    : __psIOErrorDownCaseFirst(gist) + " (error code: " + __psIOErrorCodeString(code) + ", " + __psIOErrorDownCaseFirst(details) + ")\\n  file: " + fn;`,
      `const __psIOErrorOtherToString = (gist: string, code: UInt32, details: string | undefined): string =>`,
      `  details === undefined`,
      `    ? __psIOErrorDownCaseFirst(gist) + " (error code: " + __psIOErrorCodeString(code) + ")"`,
      `    : __psIOErrorDownCaseFirst(gist) + " (error code: " + __psIOErrorCodeString(code) + ", " + __psIOErrorDownCaseFirst(details) + ")";`,
      `const __psIOErrorOptionString = (value: any): string | undefined => {`,
      `  if (value?.tag === "None") return undefined;`,
      `  if (value?.tag === "Some" && typeof value.value === "string") return value.value;`,
      `  throw new Error("Malformed Option String in IO.Error");`,
      `};`,
      `const __psIOErrorToString = (error: any): string => {`,
      `  if (!error || error.__proofscriptIOErrorBrand !== "IO.Error" || typeof error.tag !== "string")`,
      `    throw new Error("Unmapped host IO.Error cannot be stringified");`,
      `  switch (error.tag) {`,
      `    case "unexpectedEof": return "end of file";`,
      `    case "inappropriateType": { const fn = __psIOErrorOptionString(error.filename); return fn === undefined ? __psIOErrorOtherToString("inappropriate type", error.osCode, error.details) : __psIOErrorFopenToString("inappropriate type", fn, error.osCode, error.details); }`,
      `    case "interrupted": return __psIOErrorFopenToString("interrupted system call", error.filename, error.osCode, error.details);`,
      `    case "invalidArgument": { const fn = __psIOErrorOptionString(error.filename); return fn === undefined ? __psIOErrorOtherToString("invalid argument", error.osCode, error.details) : __psIOErrorFopenToString("invalid argument", fn, error.osCode, error.details); }`,
      `    case "noFileOrDirectory": return __psIOErrorFopenToString("no such file or directory", error.filename, error.osCode, undefined);`,
      `    case "noSuchThing": { const fn = __psIOErrorOptionString(error.filename); return fn === undefined ? __psIOErrorOtherToString("no such thing", error.osCode, error.details) : __psIOErrorFopenToString("no such thing", fn, error.osCode, error.details); }`,
      `    case "permissionDenied": { const fn = __psIOErrorOptionString(error.filename); return fn === undefined ? __psIOErrorOtherToString(error.details, error.osCode, undefined) : __psIOErrorFopenToString(error.details, fn, error.osCode, undefined); }`,
      `    case "resourceExhausted": { const fn = __psIOErrorOptionString(error.filename); return fn === undefined ? __psIOErrorOtherToString("resource exhausted", error.osCode, error.details) : __psIOErrorFopenToString("resource exhausted", fn, error.osCode, error.details); }`,
      `    case "alreadyExists": { const fn = __psIOErrorOptionString(error.filename); return fn === undefined ? __psIOErrorOtherToString("already exists", error.osCode, error.details) : __psIOErrorFopenToString("already exists", fn, error.osCode, error.details); }`,
      `    case "otherError": return __psIOErrorOtherToString(error.details, error.osCode, undefined);`,
      `    case "resourceBusy": return __psIOErrorOtherToString("resource busy", error.osCode, error.details);`,
      `    case "resourceVanished": return __psIOErrorOtherToString("resource vanished", error.osCode, error.details);`,
      `    case "hardwareFault": return __psIOErrorOtherToString("hardware fault", error.osCode, undefined);`,
      `    case "illegalOperation": return __psIOErrorOtherToString("illegal operation", error.osCode, error.details);`,
      `    case "protocolError": return __psIOErrorOtherToString("protocol error", error.osCode, error.details);`,
      `    case "timeExpired": return __psIOErrorOtherToString("time expired", error.osCode, error.details);`,
      `    case "unsatisfiedConstraints": return __psIOErrorOtherToString("directory not empty", error.osCode, undefined);`,
      `    case "unsupportedOperation": return __psIOErrorOtherToString("unsupported operation", error.osCode, error.details);`,
      `    case "userError": return error.msg;`,
      `    default: throw new Error("Unknown structural IO.Error constructor: " + error.tag);`,
      `  }`,
      `};`,
      `export const instToStringIOError: ToString<{ readonly __proofscriptIOErrorBrand: "IO.Error" }> = { toString: __psIOErrorToString };`,
    ].join("\n"));
  },
};

export default plugin;
