import {BinderInfo,CoreArtifact,Level,Term,binderInfoOf,collectConstNames,levelDefEq,levelOfNat,levelToNat,normalizeLevel} from "@proofscript/kernel";

/**
 * Emit a Lean 4 oracle/interoperability artifact from checked ProofScript Core.
 *
 * This printer intentionally does not reuse the kernel's human-facing pretty
 * printer for universe levels: Lean concrete syntax needs precedence-safe
 * parentheses, especially for max/imax/succ combinations.
 */
export function emitLeanArtifact(artifact:CoreArtifact):string{
  const lines=["/- Generated by ProofScript standalone production bootstrap.","   Semantic target: Lean 4.33.1.","   This is an oracle/interoperability artifact, not ProofScript source. -/",""];
  const universes:string[]=[];const seen=new Set<string>();for(const d of artifact.declarations)for(const p of d.levelParams)if(!seen.has(p)){seen.add(p);universes.push(p);}if(universes.length)lines.push(`universe ${universes.join(" ")}`,"");
  const classByName=new Map(artifact.typeclasses.classes.map(c=>[c.name,c] as const));
  const instanceByName=new Map(artifact.typeclasses.instances.map(i=>[i.name,i] as const));
  const classProjectionNames=new Set<string>();for(const c of artifact.typeclasses.classes)for(const f of c.fields)classProjectionNames.add(`${c.name}.${f.name}`);
  const nameMap=buildLeanNameMap(artifact);
  const nativeClassMirrors=new Set<string>();
  for(const d of artifact.declarations){
    if(d.kind==="inductive"&&d.name==="Add"&&isCanonicalLeanAddMirror(d))nativeClassMirrors.add("Add");
    if(d.kind==="inductive"&&d.name==="HAdd"&&isCanonicalLeanHAddMirror(d))nativeClassMirrors.add("HAdd");
  }
  const noncomputable=computeNoncomputableDefinitions(artifact,classProjectionNames);
  if(noncomputable.size)lines.push("/- Definitions using explicit generated recursors are marked noncomputable for Lean source acceptance.\n   Kernel reduction remains available; this does not add axioms or change Core checking. -/","");
  for(const d of artifact.declarations){
    // Production P3 mirrors Lean's primitive Int declaration byte-for-shape in
    // checked Core so the standalone kernel can validate Int terms without
    // trusting Lean.  The oracle source must not redeclare Lean's builtin Int;
    // suppress only the exact canonical two-constructor mirror.
    if(d.kind==="inductive"&&d.name==="Int"&&isCanonicalLeanIntMirror(d)) continue;
    if(d.kind==="inductive"&&nativeClassMirrors.has(d.name)) continue;
    if(d.kind==="definition"&&d.name==="Add.add"&&isCanonicalLeanAddProjection(d)) continue;
    if(d.kind==="definition"&&d.name==="HAdd.hAdd"&&isCanonicalLeanHAddProjection(d)) continue;
    const emittedName=mapName(d.name,nameMap);
    const cls=classByName.get(d.name);
    if(cls&&d.kind==="inductive"){
      let classTail=d.type;const paramNames:string[]=[];const renderedParams:string[]=[];
      for(let i=0;i<cls.numParams;i++){
        if(classTail.tag!=="pi")throw new Error(`class ${cls.name} parameter telescope mismatch during Lean emission`);
        const meta=cls.params[i];const pname=meta?.name||`p${i}`;
        renderedParams.push(emitBinder(pname,emitTerm(classTail.domain,paramNames,nameMap),meta?.binderInfo??binderInfoOf(classTail)));
        paramNames.push(pname);classTail=classTail.body;
      }
      const header=renderedParams.length?`class ${emittedName} ${renderedParams.join(" ")} where`:`class ${emittedName} where`;lines.push(header);
      for(const f of cls.fields){let ft=f.type;for(let i=0;i<cls.numParams;i++){if(ft.tag!=="pi")throw new Error(`class field ${cls.name}.${f.name} metadata telescope mismatch`);ft=ft.body;}lines.push(`  ${f.name} : ${emitTerm(ft,paramNames,nameMap)}`);}
      lines.push("");continue;
    }
    if(classProjectionNames.has(d.name))continue;
    const inst=instanceByName.get(d.name);
    if(inst&&d.kind==="definition"){
      const prio=inst.priority===1000?"":` (priority := ${inst.priority})`;
      const nm=inst.anonymous?"":` ${emittedName}`;
      const nc=noncomputable.has(d.name)?"noncomputable ":"";
      lines.push(`${nc}instance${prio}${nm} : ${emitTerm(d.type,[],nameMap)} := ${emitTerm(d.value,[],nameMap)}`,"");continue;
    }
    if(d.kind==="axiom")lines.push(`axiom ${emittedName} : ${emitTerm(d.type,[],nameMap)}`);
    else if(d.kind==="theorem")lines.push(`theorem ${emittedName} : ${emitTerm(d.type,[],nameMap)} := ${emitTerm(d.value,[],nameMap)}`);
    else if(d.kind==="definition"){
      const nc=noncomputable.has(d.name)?"noncomputable ":"";
      lines.push(`${nc}${d.reducibility==="abbrev"?"abbrev":"def"} ${emittedName} : ${emitTerm(d.type,[],nameMap)} := ${emitTerm(d.value,[],nameMap)}`);
    }
    else if(d.kind==="opaque")lines.push(`opaque ${emittedName} : ${emitTerm(d.type,[],nameMap)} := ${emitTerm(d.value,[],nameMap)}`);
    else if(d.kind==="example")lines.push(`example : ${emitTerm(d.type,[],nameMap)} := ${emitTerm(d.value,[],nameMap)}`);
    else if(d.kind==="quot")lines.push("/- Lean's built-in Quot/Quot.mk/Quot.lift/Quot.ind correspond to this checked Core quotient declaration. -/");
    else if(d.kind==="mutualInductive"){
      lines.push("mutual");
      const mutualNames=d.inductives.map(m=>m.name);
      for(const m of d.inductives){
        let tail=m.type;const paramNames:string[]=[];const renderedParams:string[]=[];
        for(let pi=0;pi<m.numParams;pi++){
          if(tail.tag!=="pi")throw new Error(`mutual inductive ${m.name} parameter telescope mismatch during Lean emission`);
          const pname=`p${pi}`;renderedParams.push(emitBinder(pname,emitTerm(tail.domain,paramNames,nameMap),binderInfoOf(tail)));paramNames.push(pname);tail=tail.body;
        }
        const params=renderedParams.length?` ${renderedParams.join(" ")}`:"";
        lines.push(`  inductive ${mapName(m.name,nameMap)}${params} : ${emitTerm(tail,paramNames,nameMap)} where`);
        for(const c of m.constructors){
          const short=c.name.startsWith(`${m.name}.`)?c.name.slice(m.name.length+1):mapName(c.name,nameMap);
          let ctorTail=c.type;for(let pi=0;pi<m.numParams;pi++){if(ctorTail.tag!=="pi")throw new Error(`mutual constructor ${c.name} parameter telescope mismatch during Lean emission`);ctorTail=ctorTail.body;}
          let rendered=emitTerm(ctorTail,paramNames,nameMap);
          for(const mn of mutualNames){const mapped=mapName(mn,nameMap);rendered=rendered.replaceAll(`_root_.${mapped}`,mapped);}
          lines.push(`  | ${short} : ${rendered}`);
        }
      }
      lines.push("end");
    }
    else {lines.push(`inductive ${emittedName} : ${emitTerm(d.type,[],nameMap)} where`);for(const c of d.constructors){const short=c.name.startsWith(`${d.name}.`)?c.name.slice(d.name.length+1):mapName(c.name,nameMap);lines.push(`| ${short} : ${emitInductiveConstructorType(c.type,d.name,nameMap)}`);}}
    lines.push("");
  }return lines.join("\n");
}

function canonicalShape(value:unknown):string{
  const normalize=(v:unknown):unknown=>{
    if(Array.isArray(v))return v.map(normalize);
    if(v&&typeof v==="object")return Object.fromEntries(Object.entries(v as Record<string,unknown>).filter(([k,x])=>!(k==="binderInfo"&&x==="explicit")).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,normalize(x)]));
    return v;
  };
  return JSON.stringify(normalize(value));
}
function coreC(name:string):Term{return{tag:"const",name,levels:[]};}
function coreB(index:number):Term{return{tag:"bvar",index};}
function corePi(domain:Term,body:Term):Term{return{tag:"pi",domain,body,binderInfo:"explicit"};}
function coreLam(domain:Term,body:Term):Term{return{tag:"lam",domain,body,binderInfo:"explicit"};}
function coreApp(fn:Term,arg:Term):Term{return{tag:"app",fn,arg};}
function coreApps(fn:Term,args:Term[]):Term{return args.reduce(coreApp,fn);}
function coreSort1():Term{return{tag:"sort",level:levelOfNat(1)};}

function isCanonicalLeanAddMirror(d:Extract<CoreArtifact["declarations"][number],{kind:"inductive"}>):boolean{
  const S1=coreSort1(), addFn=corePi(coreB(0),corePi(coreB(1),coreB(2)));
  const expected={kind:"inductive",name:"Add",levelParams:[],type:corePi(S1,S1),numParams:1,numIndices:0,constructors:[{name:"Add.mk",type:corePi(S1,corePi(addFn,coreApps(coreC("Add"),[coreB(1)])))}]};
  return canonicalShape(d)===canonicalShape(expected);
}
function isCanonicalLeanHAddMirror(d:Extract<CoreArtifact["declarations"][number],{kind:"inductive"}>):boolean{
  const S1=coreSort1(), hAddType=corePi(coreB(2),corePi(coreB(2),coreB(2)));
  const expected={kind:"inductive",name:"HAdd",levelParams:[],type:corePi(S1,corePi(S1,corePi(S1,S1))),numParams:3,numIndices:0,constructors:[{name:"HAdd.mk",type:corePi(S1,corePi(S1,corePi(S1,corePi(hAddType,coreApps(coreC("HAdd"),[coreB(3),coreB(2),coreB(1)])))))}]};
  return canonicalShape(d)===canonicalShape(expected);
}
function isCanonicalLeanAddProjection(d:Extract<CoreArtifact["declarations"][number],{kind:"definition"}>):boolean{
  const S1=coreSort1(), instanceType=coreApps(coreC("Add"),[coreB(0)]);
  const expected={kind:"definition",name:"Add.add",levelParams:[],type:corePi(S1,corePi(instanceType,corePi(coreB(1),corePi(coreB(2),coreB(3))))),value:coreLam(S1,coreLam(instanceType,{tag:"proj",typeName:"Add",index:0,expr:coreB(0)})),reducibility:"regular"};
  return canonicalShape(d)===canonicalShape(expected);
}
function isCanonicalLeanHAddProjection(d:Extract<CoreArtifact["declarations"][number],{kind:"definition"}>):boolean{
  const S1=coreSort1(), instanceType=coreApps(coreC("HAdd"),[coreB(2),coreB(1),coreB(0)]);
  const expected={kind:"definition",name:"HAdd.hAdd",levelParams:[],type:corePi(S1,corePi(S1,corePi(S1,corePi(instanceType,corePi(coreB(3),corePi(coreB(3),coreB(3))))))),value:coreLam(S1,coreLam(S1,coreLam(S1,coreLam(instanceType,{tag:"proj",typeName:"HAdd",index:0,expr:coreB(0)})))),reducibility:"regular"};
  return canonicalShape(d)===canonicalShape(expected);
}

function isCanonicalLeanIntMirror(d:Extract<CoreArtifact["declarations"][number],{kind:"inductive"}>):boolean{
  if(d.levelParams.length!==0||d.numParams!==0||d.numIndices!==0||d.constructors.length!==2)return false;
  if(d.type.tag!=="sort"||!levelDefEq(d.type.level,levelOfNat(1)))return false;
  const checkCtor=(index:number,name:string):boolean=>{
    const ctor=d.constructors[index];
    if(!ctor||ctor.name!==name||ctor.type.tag!=="pi"||binderInfoOf(ctor.type)!=="explicit")return false;
    const dom=ctor.type.domain, body=ctor.type.body;
    return dom.tag==="const"&&dom.name==="Nat"&&dom.levels.length===0
      && body.tag==="const"&&body.name==="Int"&&body.levels.length===0;
  };
  return checkCtor(0,"Int.ofNat")&&checkCtor(1,"Int.negSucc");
}

/** Lean reserves equation-compiler names such as `f.eq_1` once `f` exists. */
function buildLeanNameMap(artifact:CoreArtifact):Map<string,string>{
  const out=new Map<string,string>();
  for(const d of artifact.declarations){
    const m=/^(.*)\.eq_(\d+)$/.exec(d.name);
    if(m)out.set(d.name,`${m[1]}.proofscript_eq_${m[2]}`);
  }
  return out;
}
function mapName(name:string,nameMap:Map<string,string>):string{return nameMap.get(name)??name;}
function emitConstName(name:string,nameMap:Map<string,string>):string{return `_root_.${mapName(name,nameMap)}`;}

/**
 * Lean's native code generator intentionally rejects direct use of user
 * recursors in executable definitions. ProofScript Core legitimately lowers
 * projections/matches to recursors, so mark only the affected definitions and
 * their definition dependencies noncomputable in the emitted oracle source.
 */
function computeNoncomputableDefinitions(artifact:CoreArtifact,skippedDefinitions:Set<string>):Set<string>{
  const customRecursors=new Set(["Eq.rec","Nat.rec","Bool.rec","Int.rec","Decidable.rec",...artifact.declarations.filter(d=>d.kind==="inductive").map(d=>`${d.name}.rec`)]);
  // Class projections are reconstructed by Lean from `class ... where` and are
  // therefore computable there even though ProofScript Core lowers them through
  // the class recursor. Do not propagate their Core implementation detail.
  const defs:Extract<CoreArtifact["declarations"][number],{kind:"definition"}>[]=[];
  for(const d of artifact.declarations)if(d.kind==="definition"&&!skippedDefinitions.has(d.name))defs.push(d);
  const out=new Set<string>();let changed=true;
  while(changed){changed=false;for(const d of defs){if(out.has(d.name))continue;const refs=collectConstNames(d.value);if([...refs].some(n=>customRecursors.has(n)||out.has(n))){out.add(d.name);changed=true;}}}
  return out;
}

function emitInductiveConstructorType(term:Term,selfName:string,nameMap:Map<string,string>):string{
  const rendered=emitTerm(term,[],nameMap);
  const mapped=mapName(selfName,nameMap);
  return rendered.replaceAll(`_root_.${mapped}`,mapped);
}

function emitLevel(level:Level):string{
  const n=normalizeLevel(level);
  const nat=levelToNat(n);if(nat!==undefined)return String(nat);
  switch(n.tag){
    case"zero":return"0";
    case"param":return n.name;
    case"mvar":throw new Error(`universe metavariable ${n.name} cannot be emitted to Lean source`);
    case"succ":return`${emitLevelAtom(n.of)} + 1`;
    case"max":return`max ${emitLevelAtom(n.left)} ${emitLevelAtom(n.right)}`;
    case"imax":return`imax ${emitLevelAtom(n.left)} ${emitLevelAtom(n.right)}`;
  }
}
function emitLevelAtom(level:Level):string{const n=normalizeLevel(level);return n.tag==="zero"||n.tag==="param"?emitLevel(n):`(${emitLevel(n)})`;}
function emitSortLevel(level:Level):string{const n=normalizeLevel(level);return n.tag==="zero"||n.tag==="param"?emitLevel(n):`(${emitLevel(n)})`;}

function emitTerm(term:Term,names:string[],nameMap:Map<string,string>):string{switch(term.tag){case"sort":if(levelDefEq(term.level,{tag:"zero"}))return"Prop";if(term.level.tag==="succ")return levelDefEq(term.level,levelOfNat(1))?"Type":`Type ${emitSortLevel(term.level.of)}`;return`Sort ${emitSortLevel(term.level)}`;case"bvar":{const n=names[names.length-1-term.index];if(!n)throw new Error(`invalid de Bruijn index during Lean emission: #${term.index}`);return n;}case"const":{const suffix=term.levels.length?`.{${term.levels.map(emitLevel).join(", ")}}`:"";return`${emitConstName(term.name,nameMap)}${suffix}`;}case"lit":{if(term.literal.tag==="nat")return String(term.literal.value);throw new Error("Lean source emission for trusted Core string literals is not implemented");}case"app":{const args:Term[]=[];let head:Term=term;while(head.tag==="app"){args.unshift(head.arg);head=head.fn;}if(head.tag==="const")return`(@${emitTerm(head,names,nameMap)} ${args.map(a=>emitTerm(a,names,nameMap)).join(" ")})`;let out=emitTerm(head,names,nameMap);for(const a of args)out=`(${out} ${emitTerm(a,names,nameMap)})`;return out;}case"lam":{const n=fresh(names);return`(fun ${emitBinder(n,emitTerm(term.domain,names,nameMap),binderInfoOf(term))} => ${emitTerm(term.body,[...names,n],nameMap)})`;}case"pi":{const n=fresh(names);return`(∀ ${emitBinder(n,emitTerm(term.domain,names,nameMap),binderInfoOf(term))}, ${emitTerm(term.body,[...names,n],nameMap)})`;}case"let":{const n=fresh(names);const kw=term.nondep?"have":"let";return`(${kw} ${n} : ${emitTerm(term.type,names,nameMap)} := ${emitTerm(term.value,names,nameMap)}; ${emitTerm(term.body,[...names,n],nameMap)})`;}case"proj":throw new Error(`Lean source emission for raw kernel projection ${term.typeName}.${term.index} is not implemented; use the exact kernel differential harness`);}}
function fresh(names:string[]):string{let i=names.length,n=`x${i}`;while(names.includes(n))n=`x${++i}`;return n;}

function emitBinder(name:string,type:string,info:BinderInfo):string{switch(info){case"explicit":return`(${name} : ${type})`;case"implicit":return`{${name} : ${type}}`;case"strictImplicit":return`⦃${name} : ${type}⦄`;case"instImplicit":return`[${name} : ${type}]`;}}
