import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
for (const file of ["package.json", "language-configuration.json", "syntaxes/proofscript.tmLanguage.json"]) JSON.parse(fs.readFileSync(path.join(root, file), "utf8"));
for (const file of ["src/extension.js", "README.md", "media/proofscript-view.svg", "media/kernel-verified.svg", "media/frontend-checked.svg", "server/run-lsp.mjs"]) if (!fs.existsSync(path.join(root, file))) throw new Error(`missing ${file}`);
const syntax = spawnSync(process.execPath, ["--check", path.join(root, "src/extension.js")], { encoding: "utf8" });
if (syntax.status !== 0) throw new Error(syntax.stderr || syntax.stdout);
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
if (pkg.version !== "0.46.0") throw new Error(`unexpected version ${pkg.version}`);
if (pkg.activationEvents) throw new Error("activationEvents should be generated by VS Code");
if (!pkg.contributes?.viewsContainers?.secondarySidebar?.some((item) => item.id === "proofscript")) throw new Error("secondary-side-bar container missing");
if (!pkg.contributes?.views?.proofscript?.some((item) => item.id === "proofscript.infoview" && item.type === "webview")) throw new Error("Infoview missing");

if (!pkg.contributes?.commands?.some((item) => item.command === "proofscript.doctor" && /Doctor/.test(item.title))) throw new Error("doctor command missing");
const source = fs.readFileSync(path.join(root, "src/extension.js"), "utf8");
for (const needle of ["Goals accomplished!", "Expected type", "Result type", "Context", "Suggestions", "Hint:", "Details", "proofscript/lint", "proofscript/documentStatus", "proofscript/proofState", "proofscript/semanticInfo", "proofscript/declarationStatuses", "proofscript/serverStats", "proofscript.doctor", "proofscript.showDocumentStatus", "proofscript.copyExpectedType", "proofscript.copyCurrentGoal", "proofscript.copyProofState", "lastDocumentStatusByUri", "formatProofStateSummary", "EXPECTED_LSP_PROTOCOL_VERSION", "ProofScript LSP protocol mismatch", "registerCodeActionsProvider", "registerSignatureHelpProvider", "registerReferenceProvider", "registerRenameProvider", "registerWorkspaceSymbolProvider", "workspace/didChangeWatchedFiles", "kernel-verified.svg", "theorem-error.svg", "warning.svg", "theoremErrorDecoration", "warningDecoration", "testing.iconPassed", "ProofScript Status", "statusBar", "bundled ProofScript LSP", "$/cancelRequest", "Ignoring stale diagnostics", "contentChanges: changes", "additionalTextEdits", "SourceOrganizeImports"]) if (!source.includes(needle)) throw new Error(`missing ${needle}`);
console.log("✓ VS Code project semantics: Lean-like Infoview plus incremental edits, semanticInfo, cancellation-aware requests, stale-result guards, diagnostics, recovery, and gutter semantics passed");
