import fs from "node:fs";
import assert from "node:assert/strict";
import { checkSource } from "../packages/frontend/dist/index.js";
import { decodeArtifact } from "../packages/kernel-codec/dist/index.js";
import { Environment, checkAndAddDeclaration, kernelWhnf, pretty, defEq } from "../packages/kernel/dist/index.js";

const source=fs.readFileSync(new URL("../packages/std/src/Bootstrap/Foundation.ps",import.meta.url),"utf8");
const foundation=checkSource(source);
assert.equal(foundation.summary.status,"accepted");
assert.equal(foundation.artifact.formatVersion,12);
assert.equal(foundation.artifact.implementationProfile,"K3c-section-vars0");
assert.deepEqual(foundation.summary.declarations.map(d=>d.name),["Eq","Nat","Bool","Unit","Int","Int.neg","Int.add","Int.sub","Int.beq","String","Option","Option.isSome","Option.isNone","Option.getD","Option.orElse","Option.fold","Option.any","List","List.map","List.foldl","List.filter","List.append","List.length","List.range","List.replicate","List.isEmpty","List.head?","List.get?","List.take","List.takeWhile","List.dropWhile","List.drop","List.last?","List.tail?","List.reverse","List.any","List.all","List.find?","List.countP","List.singleton","Option.toList","Array","Array.size","Array.range","Array.replicate","Array.toList","List.toArray","Array.get?","Array.take","Array.takeWhile","Array.dropWhile","Array.drop","Array.head?","Array.last?","Array.tail?","Array.map","Array.foldl","Array.filter","Array.append","Array.isEmpty","Array.reverse","Array.any","Array.all","Array.find?","Array.countP","Array.singleton","Option.toArray","Option.filter","Option.flatten","Except","Except.isOk","Except.isError","Except.getD","Except.orElse","Except.toOption","Except.toError","Except.getErrorD","Except.swap","Except.fold","Except.bimap","Except.toList","Option.toExcept","Except.toArray","Except.mapError","Except.flatten","Option.map","Except.map","Option.bind","Except.bind","Nat.add","Nat.pred","Nat.sub","Nat.mul","Nat.leb","Nat.beq","Nat.ltb","Bool.not","Bool.xor"]);
assert.deepEqual(foundation.summary.assumptions,["Array.all","Array.any","Array.append","Array.countP","Array.drop","Array.dropWhile","Array.filter","Array.find?","Array.foldl","Array.get?","Array.head?","Array.isEmpty","Array.last?","Array.map","Array.range","Array.replicate","Array.reverse","Array.size","Array.tail?","Array.take","Array.takeWhile","Array.toList","Except.bind","Except.map","Int.add","Int.beq","Int.neg","Int.sub","List.all","List.any","List.append","List.countP","List.drop","List.dropWhile","List.filter","List.find?","List.foldl","List.get?","List.head?","List.isEmpty","List.last?","List.length","List.map","List.range","List.replicate","List.reverse","List.tail?","List.take","List.takeWhile","List.toArray","Option.bind","Option.map"]);

const replay=decodeArtifact(JSON.parse(JSON.stringify(foundation.artifact)));
const env=new Environment();for(const d of replay.declarations)checkAndAddDeclaration(env,d);
for(const name of ["Eq.refl","Eq.rec","Nat.zero","Nat.succ","Nat.rec","Bool.false","Bool.true","Bool.rec","Unit.unit","Unit.rec","Int.token","Int.rec","Int.neg","Int.add","Int.sub","Int.beq","String.token","String.rec","Option.none","Option.some","Option.rec","Option.isSome","Option.isNone","Option.getD","Option.orElse","Option.fold","Option.any","List.nil","List.cons","List.rec","List.map","List.foldl","List.filter","List.append","List.length","List.range","List.replicate","List.isEmpty","List.head?","List.get?","List.take","List.takeWhile","List.dropWhile","List.drop","List.last?","List.tail?","List.reverse","List.any","List.all","List.find?","List.countP","List.singleton","Option.toList","Array.mk","Array.rec","Array.size","Array.range","Array.replicate","Array.toList","List.toArray","Array.get?","Array.take","Array.takeWhile","Array.dropWhile","Array.drop","Array.head?","Array.last?","Array.tail?","Array.map","Array.foldl","Array.filter","Array.append","Array.isEmpty","Array.reverse","Array.any","Array.all","Array.find?","Array.countP","Except.error","Except.ok","Except.rec","Except.isOk","Except.isError","Except.getD","Except.orElse","Except.toOption","Except.toError","Except.getErrorD","Except.swap","Except.fold","Except.bimap","Except.toList","Option.toExcept","Except.toArray","Except.mapError","Except.flatten","Option.map","Except.map","Option.bind","Except.bind","Nat.add","Nat.pred","Nat.sub","Nat.mul","Nat.leb","Nat.beq","Nat.ltb","Bool.not","Bool.xor"])assert.ok(env.has(name),`missing ${name}`);

const C=(name,levels=[])=>({tag:"const",name,levels});const A=(fn,arg)=>({tag:"app",fn,arg});const many=(fn,args)=>args.reduce((f,a)=>A(f,a),fn);
const zero=C("Nat.zero"),succ=C("Nat.succ"),add=C("Nat.add"),pred=C("Nat.pred"),sub=C("Nat.sub"),mul=C("Nat.mul"),leb=C("Nat.leb"),beq=C("Nat.beq"),ltb=C("Nat.ltb"),bnot=C("Bool.not"),bxor=C("Bool.xor"),btrue=C("Bool.true"),bfalse=C("Bool.false");
assert.equal(pretty(kernelWhnf(env,many(add,[zero,zero]))),"Nat.zero");
assert.equal(defEq(env,[],many(pred,[A(succ,A(succ,zero))]),A(succ,zero)),true);
assert.equal(defEq(env,[],many(sub,[A(succ,A(succ,A(succ,zero))),A(succ,A(succ,zero))]),A(succ,zero)),true);
assert.equal(defEq(env,[],many(sub,[A(succ,zero),A(succ,A(succ,zero))]),zero),true);
assert.equal(defEq(env,[],many(mul,[A(succ,A(succ,zero)),A(succ,A(succ,A(succ,zero)))]),A(succ,A(succ,A(succ,A(succ,A(succ,A(succ,zero))))))),true);
assert.equal(defEq(env,[],many(leb,[A(succ,A(succ,zero)),A(succ,A(succ,A(succ,zero)))]),btrue),true);
assert.equal(defEq(env,[],many(leb,[A(succ,A(succ,A(succ,zero))),A(succ,A(succ,zero))]),bfalse),true);
assert.equal(defEq(env,[],many(beq,[A(succ,A(succ,zero)),A(succ,A(succ,zero))]),btrue),true);
assert.equal(defEq(env,[],many(beq,[A(succ,A(succ,zero)),A(succ,A(succ,A(succ,zero)))]),bfalse),true);
assert.equal(defEq(env,[],many(ltb,[A(succ,A(succ,zero)),A(succ,A(succ,A(succ,zero)))]),btrue),true);
assert.equal(defEq(env,[],many(bnot,[btrue]),bfalse),true);
assert.equal(defEq(env,[],many(bnot,[bfalse]),btrue),true);
assert.equal(defEq(env,[],many(bxor,[btrue,bfalse]),btrue),true);
assert.equal(defEq(env,[],many(bxor,[btrue,btrue]),bfalse),true);
const intNeg=C("Int.neg"),intAdd=C("Int.add"),intSub=C("Int.sub"),intBeq=C("Int.beq");
const i=(value)=>({tag:"lit",literal:{tag:"int",value}});
assert.equal(defEq(env,[],many(intNeg,[i(5)]),i(-5)),true);
assert.equal(defEq(env,[],many(intAdd,[i(-2),i(5)]),i(3)),true);
assert.equal(defEq(env,[],many(intSub,[i(-2),i(5)]),i(-7)),true);
assert.equal(defEq(env,[],many(intBeq,[i(-3),many(intNeg,[i(3)])]),btrue),true);
assert.equal(defEq(env,[],many(intBeq,[i(-3),i(3)]),bfalse),true);
const natType=C("Nat");
const listNil=many(C("List.nil"),[natType]);
const listOneTwo=many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:2}},listNil])]);
const arrayOneTwo=many(C("Array.mk"),[natType,listOneTwo]);
const listSingletonNine=many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:9}},listNil]);
assert.equal(defEq(env,[],many(C("List.singleton"),[natType,{tag:"lit",literal:{tag:"nat",value:9}}]),listSingletonNine),true);
assert.equal(defEq(env,[],many(C("Array.singleton"),[natType,{tag:"lit",literal:{tag:"nat",value:9}}]),many(C("Array.mk"),[natType,listSingletonNine])),true);
assert.equal(defEq(env,[],many(C("Array.size"),[natType,arrayOneTwo]),{tag:"lit",literal:{tag:"nat",value:2}}),true);
assert.equal(defEq(env,[],many(C("Array.range"),[{tag:"lit",literal:{tag:"nat",value:0}}]),many(C("Array.mk"),[natType,listNil])),true);
assert.equal(defEq(env,[],many(C("Array.range"),[{tag:"lit",literal:{tag:"nat",value:3}}]),many(C("Array.mk"),[natType,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:0}},many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:2}},listNil])])])])),true);
assert.equal(defEq(env,[],many(C("Array.replicate"),[natType,{tag:"lit",literal:{tag:"nat",value:0}},{tag:"lit",literal:{tag:"nat",value:7}}]),many(C("Array.mk"),[natType,listNil])),true);
assert.equal(defEq(env,[],many(C("Array.replicate"),[natType,{tag:"lit",literal:{tag:"nat",value:2}},{tag:"lit",literal:{tag:"nat",value:7}}]),many(C("Array.mk"),[natType,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:7}},many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:7}},listNil])])])),true);
assert.equal(defEq(env,[],many(C("Array.toList"),[natType,arrayOneTwo]),listOneTwo),true);
assert.equal(defEq(env,[],many(C("List.toArray"),[natType,listOneTwo]),arrayOneTwo),true);
assert.equal(defEq(env,[],many(C("Array.get?"),[natType,arrayOneTwo,{tag:"lit",literal:{tag:"nat",value:0}}]),many(C("Option.some"),[natType,{tag:"lit",literal:{tag:"nat",value:1}}])),true);
assert.equal(defEq(env,[],many(C("Array.get?"),[natType,arrayOneTwo,{tag:"lit",literal:{tag:"nat",value:2}}]),many(C("Option.none"),[natType])),true);
assert.equal(defEq(env,[],many(C("Array.head?"),[natType,arrayOneTwo]),many(C("Option.some"),[natType,{tag:"lit",literal:{tag:"nat",value:1}}])),true);
assert.equal(defEq(env,[],many(C("Array.head?"),[natType,many(C("Array.mk"),[natType,listNil])]),many(C("Option.none"),[natType])),true);
assert.equal(defEq(env,[],many(C("Array.last?"),[natType,arrayOneTwo]),many(C("Option.some"),[natType,{tag:"lit",literal:{tag:"nat",value:2}}])),true);
assert.equal(defEq(env,[],many(C("Array.last?"),[natType,many(C("Array.mk"),[natType,listNil])]),many(C("Option.none"),[natType])),true);
const arrayNatType=many(C("Array"),[natType]);
assert.equal(defEq(env,[],many(C("Array.tail?"),[natType,arrayOneTwo]),many(C("Option.some"),[arrayNatType,many(C("Array.mk"),[natType,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:2}},listNil])])])),true);
assert.equal(defEq(env,[],many(C("Array.tail?"),[natType,many(C("Array.mk"),[natType,listNil])]),many(C("Option.none"),[arrayNatType])),true);
const incNat={tag:"lam",domain:natType,body:many(add,[{tag:"bvar",index:0},{tag:"lit",literal:{tag:"nat",value:1}}])};

const mappedList=many(C("List.map"),[natType,natType,incNat,listOneTwo]);
const mappedListExpected=many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:2}},many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:3}},listNil])]);
assert.equal(defEq(env,[],mappedList,mappedListExpected),true);
const sumStep={tag:"lam",domain:natType,body:{tag:"lam",domain:natType,body:many(add,[{tag:"bvar",index:1},{tag:"bvar",index:0}])}};
assert.equal(defEq(env,[],many(C("List.foldl"),[natType,natType,sumStep,{tag:"lit",literal:{tag:"nat",value:0}},listOneTwo]),{tag:"lit",literal:{tag:"nat",value:3}}),true);
const mappedArray=many(C("Array.map"),[natType,natType,incNat,arrayOneTwo]);
const keepOne={tag:"lam",domain:natType,body:many(beq,[{tag:"bvar",index:0},{tag:"lit",literal:{tag:"nat",value:1}}])};
assert.equal(defEq(env,[],many(C("List.filter"),[natType,keepOne,listOneTwo]),many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},listNil])),true);
const appendedList=many(C("List.append"),[natType,listOneTwo,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:3}},listNil])]);
assert.equal(defEq(env,[],appendedList,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:2}},many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:3}},listNil])])])),true);
assert.equal(defEq(env,[],many(C("List.length"),[natType,listOneTwo]),{tag:"lit",literal:{tag:"nat",value:2}}),true);
assert.equal(defEq(env,[],many(C("List.length"),[natType,listNil]),{tag:"lit",literal:{tag:"nat",value:0}}),true);
assert.equal(defEq(env,[],many(C("List.range"),[{tag:"lit",literal:{tag:"nat",value:0}}]),listNil),true);
assert.equal(defEq(env,[],many(C("List.range"),[{tag:"lit",literal:{tag:"nat",value:3}}]),many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:0}},many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:2}},listNil])])])),true);
assert.equal(defEq(env,[],many(C("List.replicate"),[natType,{tag:"lit",literal:{tag:"nat",value:0}},{tag:"lit",literal:{tag:"nat",value:7}}]),listNil),true);
assert.equal(defEq(env,[],many(C("List.replicate"),[natType,{tag:"lit",literal:{tag:"nat",value:2}},{tag:"lit",literal:{tag:"nat",value:7}}]),many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:7}},many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:7}},listNil])])),true);
assert.equal(defEq(env,[],many(C("List.isEmpty"),[natType,listOneTwo]),bfalse),true);
assert.equal(defEq(env,[],many(C("List.isEmpty"),[natType,listNil]),btrue),true);
assert.equal(defEq(env,[],many(C("List.head?"),[natType,listOneTwo]),many(C("Option.some"),[natType,{tag:"lit",literal:{tag:"nat",value:1}}])),true);
assert.equal(defEq(env,[],many(C("List.head?"),[natType,listNil]),many(C("Option.none"),[natType])),true);
assert.equal(defEq(env,[],many(C("List.get?"),[natType,listOneTwo,{tag:"lit",literal:{tag:"nat",value:0}}]),many(C("Option.some"),[natType,{tag:"lit",literal:{tag:"nat",value:1}}])),true);
assert.equal(defEq(env,[],many(C("List.get?"),[natType,listOneTwo,{tag:"lit",literal:{tag:"nat",value:1}}]),many(C("Option.some"),[natType,{tag:"lit",literal:{tag:"nat",value:2}}])),true);
assert.equal(defEq(env,[],many(C("List.get?"),[natType,listOneTwo,{tag:"lit",literal:{tag:"nat",value:2}}]),many(C("Option.none"),[natType])),true);
assert.equal(defEq(env,[],many(C("List.get?"),[natType,listNil,{tag:"lit",literal:{tag:"nat",value:0}}]),many(C("Option.none"),[natType])),true);
assert.equal(defEq(env,[],many(C("List.take"),[natType,listOneTwo,{tag:"lit",literal:{tag:"nat",value:1}}]),many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},listNil])),true);
assert.equal(defEq(env,[],many(C("List.take"),[natType,listOneTwo,{tag:"lit",literal:{tag:"nat",value:9}}]),listOneTwo),true);
assert.equal(defEq(env,[],many(C("List.take"),[natType,listNil,{tag:"lit",literal:{tag:"nat",value:1}}]),listNil),true);
assert.equal(defEq(env,[],many(C("List.takeWhile"),[natType,keepOne,listOneTwo]),many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},listNil])),true);
assert.equal(defEq(env,[],many(C("List.takeWhile"),[natType,keepOne,listNil]),listNil),true);
assert.equal(defEq(env,[],many(C("List.dropWhile"),[natType,keepOne,listOneTwo]),many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:2}},listNil])),true);
assert.equal(defEq(env,[],many(C("List.dropWhile"),[natType,keepOne,listNil]),listNil),true);
assert.equal(defEq(env,[],many(C("List.drop"),[natType,listOneTwo,{tag:"lit",literal:{tag:"nat",value:1}}]),many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:2}},listNil])),true);
assert.equal(defEq(env,[],many(C("List.drop"),[natType,listOneTwo,{tag:"lit",literal:{tag:"nat",value:9}}]),listNil),true);
assert.equal(defEq(env,[],many(C("List.drop"),[natType,listNil,{tag:"lit",literal:{tag:"nat",value:1}}]),listNil),true);
assert.equal(defEq(env,[],many(C("List.last?"),[natType,listOneTwo]),many(C("Option.some"),[natType,{tag:"lit",literal:{tag:"nat",value:2}}])),true);
assert.equal(defEq(env,[],many(C("List.last?"),[natType,listNil]),many(C("Option.none"),[natType])),true);
const listNatType=many(C("List"),[natType]);
assert.equal(defEq(env,[],many(C("List.tail?"),[natType,listOneTwo]),many(C("Option.some"),[listNatType,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:2}},listNil])])),true);
assert.equal(defEq(env,[],many(C("List.tail?"),[natType,listNil]),many(C("Option.none"),[listNatType])),true);
assert.equal(defEq(env,[],many(C("List.reverse"),[natType,listOneTwo]),many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:2}},many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},listNil])])),true);
assert.equal(defEq(env,[],many(C("List.any"),[natType,keepOne,listOneTwo]),btrue),true);
assert.equal(defEq(env,[],many(C("List.any"),[natType,keepOne,listNil]),bfalse),true);
assert.equal(defEq(env,[],many(C("List.all"),[natType,keepOne,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},listNil])]),btrue),true);
assert.equal(defEq(env,[],many(C("List.all"),[natType,keepOne,listOneTwo]),bfalse),true);
assert.equal(defEq(env,[],many(C("List.all"),[natType,keepOne,listNil]),btrue),true);
assert.equal(defEq(env,[],many(C("List.find?"),[natType,keepOne,listOneTwo]),many(C("Option.some"),[natType,{tag:"lit",literal:{tag:"nat",value:1}}])),true);
assert.equal(defEq(env,[],many(C("List.find?"),[natType,keepOne,listNil]),many(C("Option.none"),[natType])),true);
assert.equal(defEq(env,[],many(C("List.countP"),[natType,keepOne,listOneTwo]),{tag:"lit",literal:{tag:"nat",value:1}}),true);
assert.equal(defEq(env,[],many(C("List.countP"),[natType,keepOne,listNil]),{tag:"lit",literal:{tag:"nat",value:0}}),true);
const mappedArrayExpected=many(C("Array.mk"),[natType,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:2}},many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:3}},listNil])])]);
assert.equal(defEq(env,[],mappedArray,mappedArrayExpected),true);
assert.equal(defEq(env,[],many(C("Array.foldl"),[natType,natType,sumStep,{tag:"lit",literal:{tag:"nat",value:0}},arrayOneTwo]),{tag:"lit",literal:{tag:"nat",value:3}}),true);
const optionSomeOne=many(C("Option.some"),[natType,{tag:"lit",literal:{tag:"nat",value:1}}]);
const filteredArray=many(C("Array.filter"),[natType,keepOne,arrayOneTwo]);
assert.equal(defEq(env,[],filteredArray,many(C("Array.mk"),[natType,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},listNil])])),true);
const appendedArray=many(C("Array.append"),[natType,arrayOneTwo,many(C("Array.mk"),[natType,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:3}},listNil])])]);
assert.equal(defEq(env,[],appendedArray,many(C("Array.mk"),[natType,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:2}},many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:3}},listNil])])])])),true);
assert.equal(defEq(env,[],many(C("Array.isEmpty"),[natType,arrayOneTwo]),bfalse),true);
assert.equal(defEq(env,[],many(C("Array.isEmpty"),[natType,many(C("Array.mk"),[natType,listNil])]),btrue),true);
assert.equal(defEq(env,[],many(C("Array.reverse"),[natType,arrayOneTwo]),many(C("Array.mk"),[natType,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:2}},many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},listNil])])])),true);
assert.equal(defEq(env,[],many(C("Array.any"),[natType,keepOne,arrayOneTwo]),btrue),true);
assert.equal(defEq(env,[],many(C("Array.any"),[natType,keepOne,many(C("Array.mk"),[natType,listNil])]),bfalse),true);
assert.equal(defEq(env,[],many(C("Array.all"),[natType,keepOne,many(C("Array.mk"),[natType,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},listNil])])]),btrue),true);
assert.equal(defEq(env,[],many(C("Array.all"),[natType,keepOne,arrayOneTwo]),bfalse),true);
assert.equal(defEq(env,[],many(C("Array.all"),[natType,keepOne,many(C("Array.mk"),[natType,listNil])]),btrue),true);
assert.equal(defEq(env,[],many(C("Array.find?"),[natType,keepOne,arrayOneTwo]),many(C("Option.some"),[natType,{tag:"lit",literal:{tag:"nat",value:1}}])),true);
assert.equal(defEq(env,[],many(C("Array.find?"),[natType,keepOne,many(C("Array.mk"),[natType,listNil])]),many(C("Option.none"),[natType])),true);
assert.equal(defEq(env,[],many(C("Array.countP"),[natType,keepOne,arrayOneTwo]),{tag:"lit",literal:{tag:"nat",value:1}}),true);
assert.equal(defEq(env,[],many(C("Array.countP"),[natType,keepOne,many(C("Array.mk"),[natType,listNil])]),{tag:"lit",literal:{tag:"nat",value:0}}),true);
assert.equal(defEq(env,[],many(C("Array.take"),[natType,arrayOneTwo,{tag:"lit",literal:{tag:"nat",value:1}}]),many(C("Array.mk"),[natType,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},listNil])])),true);
assert.equal(defEq(env,[],many(C("Array.take"),[natType,arrayOneTwo,{tag:"lit",literal:{tag:"nat",value:9}}]),arrayOneTwo),true);
assert.equal(defEq(env,[],many(C("Array.take"),[natType,many(C("Array.mk"),[natType,listNil]),{tag:"lit",literal:{tag:"nat",value:1}}]),many(C("Array.mk"),[natType,listNil])),true);
assert.equal(defEq(env,[],many(C("Array.takeWhile"),[natType,keepOne,arrayOneTwo]),many(C("Array.mk"),[natType,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},listNil])])),true);
assert.equal(defEq(env,[],many(C("Array.takeWhile"),[natType,keepOne,many(C("Array.mk"),[natType,listNil])]),many(C("Array.mk"),[natType,listNil])),true);
assert.equal(defEq(env,[],many(C("Array.dropWhile"),[natType,keepOne,arrayOneTwo]),many(C("Array.mk"),[natType,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:2}},listNil])])),true);
assert.equal(defEq(env,[],many(C("Array.dropWhile"),[natType,keepOne,many(C("Array.mk"),[natType,listNil])]),many(C("Array.mk"),[natType,listNil])),true);
assert.equal(defEq(env,[],many(C("Array.drop"),[natType,arrayOneTwo,{tag:"lit",literal:{tag:"nat",value:1}}]),many(C("Array.mk"),[natType,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:2}},listNil])])),true);
assert.equal(defEq(env,[],many(C("Array.drop"),[natType,arrayOneTwo,{tag:"lit",literal:{tag:"nat",value:9}}]),many(C("Array.mk"),[natType,listNil])),true);
assert.equal(defEq(env,[],many(C("Array.drop"),[natType,many(C("Array.mk"),[natType,listNil]),{tag:"lit",literal:{tag:"nat",value:1}}]),many(C("Array.mk"),[natType,listNil])),true);
const optionNone=many(C("Option.none"),[natType]);
assert.equal(defEq(env,[],many(C("Option.isSome"),[natType,optionSomeOne]),btrue),true);
assert.equal(defEq(env,[],many(C("Option.isSome"),[natType,optionNone]),bfalse),true);
assert.equal(defEq(env,[],many(C("Option.isNone"),[natType,optionSomeOne]),bfalse),true);
assert.equal(defEq(env,[],many(C("Option.isNone"),[natType,optionNone]),btrue),true);
assert.equal(defEq(env,[],many(C("Option.getD"),[natType,optionSomeOne,{tag:"lit",literal:{tag:"nat",value:99}}]),{tag:"lit",literal:{tag:"nat",value:1}}),true);
assert.equal(defEq(env,[],many(C("Option.getD"),[natType,optionNone,{tag:"lit",literal:{tag:"nat",value:99}}]),{tag:"lit",literal:{tag:"nat",value:99}}),true);
const optionSomeNinetyNine=many(C("Option.some"),[natType,{tag:"lit",literal:{tag:"nat",value:99}}]);
assert.equal(defEq(env,[],many(C("Option.orElse"),[natType,optionSomeOne,optionSomeNinetyNine]),optionSomeOne),true);
assert.equal(defEq(env,[],many(C("Option.orElse"),[natType,optionNone,optionSomeNinetyNine]),optionSomeNinetyNine),true);
const optionFoldAddOne={tag:"lam",domain:natType,body:many(add,[{tag:"bvar",index:0},{tag:"lit",literal:{tag:"nat",value:1}}])};
assert.equal(defEq(env,[],many(C("Option.fold"),[natType,natType,{tag:"lit",literal:{tag:"nat",value:99}},optionFoldAddOne,optionSomeOne]),{tag:"lit",literal:{tag:"nat",value:2}}),true);
assert.equal(defEq(env,[],many(C("Option.fold"),[natType,natType,{tag:"lit",literal:{tag:"nat",value:99}},optionFoldAddOne,optionNone]),{tag:"lit",literal:{tag:"nat",value:99}}),true);
assert.equal(defEq(env,[],many(C("Option.toList"),[natType,optionSomeOne]),many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},listNil])),true);
assert.equal(defEq(env,[],many(C("Option.toList"),[natType,optionNone]),listNil),true);
assert.equal(defEq(env,[],many(C("Option.toArray"),[natType,optionSomeOne]),many(C("Array.mk"),[natType,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},listNil])])),true);
assert.equal(defEq(env,[],many(C("Option.toArray"),[natType,optionNone]),many(C("Array.mk"),[natType,listNil])),true);
const ltTwo={tag:"lam",domain:natType,body:many(ltb,[{tag:"bvar",index:0},{tag:"lit",literal:{tag:"nat",value:2}}])};
assert.equal(defEq(env,[],many(C("Option.filter"),[natType,ltTwo,optionSomeOne]),optionSomeOne),true);
assert.equal(defEq(env,[],many(C("Option.filter"),[natType,ltTwo,many(C("Option.some"),[natType,{tag:"lit",literal:{tag:"nat",value:7}}])]),optionNone),true);
assert.equal(defEq(env,[],many(C("Option.filter"),[natType,ltTwo,optionNone]),optionNone),true);
const optionSomeOptionSomeOne=many(C("Option.some"),[many(C("Option"),[natType]),optionSomeOne]);
const optionSomeOptionNone=many(C("Option.some"),[many(C("Option"),[natType]),optionNone]);
const optionNoneOption=many(C("Option.none"),[many(C("Option"),[natType])]);
assert.equal(defEq(env,[],many(C("Option.flatten"),[natType,optionSomeOptionSomeOne]),optionSomeOne),true);
const optionAnyIsOne={tag:"lam",domain:natType,body:many(beq,[{tag:"bvar",index:0},{tag:"lit",literal:{tag:"nat",value:1}}])};
assert.equal(defEq(env,[],many(C("Option.any"),[natType,optionAnyIsOne,optionSomeOne]),btrue),true);
assert.equal(defEq(env,[],many(C("Option.any"),[natType,optionAnyIsOne,many(C("Option.some"),[natType,{tag:"lit",literal:{tag:"nat",value:2}}])]),bfalse),true);
assert.equal(defEq(env,[],many(C("Option.any"),[natType,optionAnyIsOne,optionNone]),bfalse),true);
assert.equal(defEq(env,[],many(C("Option.flatten"),[natType,optionSomeOptionNone]),optionNone),true);
assert.equal(defEq(env,[],many(C("Option.flatten"),[natType,optionNoneOption]),optionNone),true);
const addOne={tag:"lam",domain:natType,body:many(C("Option.some"),[natType,many(add,[{tag:"bvar",index:0},{tag:"lit",literal:{tag:"nat",value:1}}])])};
assert.equal(defEq(env,[],many(C("Option.bind"),[natType,natType,optionSomeOne,addOne]),many(C("Option.some"),[natType,{tag:"lit",literal:{tag:"nat",value:2}}])),true);
assert.equal(defEq(env,[],many(C("Option.bind"),[natType,natType,optionNone,addOne]),optionNone),true);
const exceptOkOne=many(C("Except.ok"),[C("String"),natType,{tag:"lit",literal:{tag:"nat",value:1}}]);
assert.equal(defEq(env,[],many(C("Except.isOk"),[C("String"),natType,exceptOkOne]),btrue),true);
const exceptError=many(C("Except.error"),[C("String"),natType,{tag:"lit",literal:{tag:"str",value:"bad"}}]);
assert.equal(defEq(env,[],many(C("Except.isOk"),[C("String"),natType,exceptError]),bfalse),true);
assert.equal(defEq(env,[],many(C("Except.isError"),[C("String"),natType,exceptOkOne]),bfalse),true);
assert.equal(defEq(env,[],many(C("Except.isError"),[C("String"),natType,exceptError]),btrue),true);
assert.equal(defEq(env,[],many(C("Except.getD"),[C("String"),natType,exceptOkOne,{tag:"lit",literal:{tag:"nat",value:99}}]),{tag:"lit",literal:{tag:"nat",value:1}}),true);
assert.equal(defEq(env,[],many(C("Except.getD"),[C("String"),natType,exceptError,{tag:"lit",literal:{tag:"nat",value:99}}]),{tag:"lit",literal:{tag:"nat",value:99}}),true);
const exceptOkNinetyNine=many(C("Except.ok"),[C("String"),natType,{tag:"lit",literal:{tag:"nat",value:99}}]);
assert.equal(defEq(env,[],many(C("Except.orElse"),[C("String"),natType,exceptOkOne,exceptOkNinetyNine]),exceptOkOne),true);
assert.equal(defEq(env,[],many(C("Except.orElse"),[C("String"),natType,exceptError,exceptOkNinetyNine]),exceptOkNinetyNine),true);
assert.equal(defEq(env,[],many(C("Except.toOption"),[C("String"),natType,exceptOkOne]),optionSomeOne),true);
assert.equal(defEq(env,[],many(C("Except.toOption"),[C("String"),natType,exceptError]),optionNone),true);
assert.equal(defEq(env,[],many(C("Except.toError"),[C("String"),natType,exceptError]),many(C("Option.some"),[C("String"),{tag:"lit",literal:{tag:"str",value:"bad"}}])),true);
assert.equal(defEq(env,[],many(C("Except.toError"),[C("String"),natType,exceptOkOne]),many(C("Option.none"),[C("String")])),true);
assert.equal(defEq(env,[],many(C("Except.getErrorD"),[C("String"),natType,exceptError,{tag:"lit",literal:{tag:"str",value:"fallback"}}]),{tag:"lit",literal:{tag:"str",value:"bad"}}),true);
assert.equal(defEq(env,[],many(C("Except.getErrorD"),[C("String"),natType,exceptOkOne,{tag:"lit",literal:{tag:"str",value:"fallback"}}]),{tag:"lit",literal:{tag:"str",value:"fallback"}}),true);
assert.equal(defEq(env,[],many(C("Except.swap"),[C("String"),natType,exceptError]),many(C("Except.ok"),[natType,C("String"),{tag:"lit",literal:{tag:"str",value:"bad"}}])),true);
assert.equal(defEq(env,[],many(C("Except.swap"),[C("String"),natType,exceptOkOne]),many(C("Except.error"),[natType,C("String"),{tag:"lit",literal:{tag:"nat",value:1}}])),true);
const exceptFoldErrorString={tag:"lam",domain:C("String"),body:{tag:"bvar",index:0}};
const exceptFoldOkString={tag:"lam",domain:natType,body:{tag:"lit",literal:{tag:"str",value:"ok"}}};
const exceptFoldErrorNat={tag:"lam",domain:C("String"),body:{tag:"lit",literal:{tag:"nat",value:0}}};
const exceptFoldOkNat={tag:"lam",domain:natType,body:many(add,[{tag:"bvar",index:0},{tag:"lit",literal:{tag:"nat",value:1}}])};
assert.equal(defEq(env,[],many(C("Except.fold"),[C("String"),natType,C("String"),exceptFoldErrorString,exceptFoldOkString,exceptError]),{tag:"lit",literal:{tag:"str",value:"bad"}}),true);
assert.equal(defEq(env,[],many(C("Except.fold"),[C("String"),natType,C("String"),exceptFoldErrorString,exceptFoldOkString,exceptOkOne]),{tag:"lit",literal:{tag:"str",value:"ok"}}),true);
assert.equal(defEq(env,[],many(C("Except.fold"),[C("String"),natType,natType,exceptFoldErrorNat,exceptFoldOkNat,exceptError]),{tag:"lit",literal:{tag:"nat",value:0}}),true);
assert.equal(defEq(env,[],many(C("Except.fold"),[C("String"),natType,natType,exceptFoldErrorNat,exceptFoldOkNat,exceptOkOne]),{tag:"lit",literal:{tag:"nat",value:2}}),true);
const exceptBimapErrorMap={tag:"lam",domain:C("String"),body:{tag:"lit",literal:{tag:"str",value:"mapped-error"}}};
const exceptBimapOkMap={tag:"lam",domain:natType,body:many(add,[{tag:"bvar",index:0},{tag:"lit",literal:{tag:"nat",value:1}}])};
assert.equal(defEq(env,[],many(C("Except.bimap"),[C("String"),C("String"),natType,natType,exceptBimapErrorMap,exceptBimapOkMap,exceptError]),many(C("Except.error"),[C("String"),natType,{tag:"lit",literal:{tag:"str",value:"mapped-error"}}])),true);
assert.equal(defEq(env,[],many(C("Except.bimap"),[C("String"),C("String"),natType,natType,exceptBimapErrorMap,exceptBimapOkMap,exceptOkOne]),many(C("Except.ok"),[C("String"),natType,{tag:"lit",literal:{tag:"nat",value:2}}])),true);
assert.equal(defEq(env,[],many(C("Except.toList"),[C("String"),natType,exceptOkOne]),many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},listNil])),true);
assert.equal(defEq(env,[],many(C("Except.toList"),[C("String"),natType,exceptError]),listNil),true);
assert.equal(defEq(env,[],many(C("Option.toExcept"),[C("String"),natType,optionSomeOne,{tag:"lit",literal:{tag:"str",value:"missing"}}]),exceptOkOne),true);
assert.equal(defEq(env,[],many(C("Option.toExcept"),[C("String"),natType,optionNone,{tag:"lit",literal:{tag:"str",value:"missing"}}]),many(C("Except.error"),[C("String"),natType,{tag:"lit",literal:{tag:"str",value:"missing"}}])),true);
assert.equal(defEq(env,[],many(C("Except.toArray"),[C("String"),natType,exceptOkOne]),many(C("Array.mk"),[natType,many(C("List.cons"),[natType,{tag:"lit",literal:{tag:"nat",value:1}},listNil])])),true);
assert.equal(defEq(env,[],many(C("Except.toArray"),[C("String"),natType,exceptError]),many(C("Array.mk"),[natType,listNil])),true);
const stringToMapped={tag:"lam",domain:C("String"),body:{tag:"lit",literal:{tag:"str",value:"mapped"}}};
assert.equal(defEq(env,[],many(C("Except.mapError"),[C("String"),C("String"),natType,stringToMapped,exceptError]),many(C("Except.error"),[C("String"),natType,{tag:"lit",literal:{tag:"str",value:"mapped"}}])),true);
assert.equal(defEq(env,[],many(C("Except.mapError"),[C("String"),C("String"),natType,stringToMapped,exceptOkOne]),exceptOkOne),true);
const exceptOkExceptOkOne=many(C("Except.ok"),[C("String"),many(C("Except"),[C("String"),natType]),exceptOkOne]);
const exceptOkExceptError=many(C("Except.ok"),[C("String"),many(C("Except"),[C("String"),natType]),exceptError]);
const exceptOuterError=many(C("Except.error"),[C("String"),many(C("Except"),[C("String"),natType]),{tag:"lit",literal:{tag:"str",value:"outer"}}]);
assert.equal(defEq(env,[],many(C("Except.flatten"),[C("String"),natType,exceptOkExceptOkOne]),exceptOkOne),true);
assert.equal(defEq(env,[],many(C("Except.flatten"),[C("String"),natType,exceptOkExceptError]),exceptError),true);
assert.equal(defEq(env,[],many(C("Except.flatten"),[C("String"),natType,exceptOuterError]),many(C("Except.error"),[C("String"),natType,{tag:"lit",literal:{tag:"str",value:"outer"}}])),true);
const exceptAddOne={tag:"lam",domain:natType,body:many(C("Except.ok"),[C("String"),natType,many(add,[{tag:"bvar",index:0},{tag:"lit",literal:{tag:"nat",value:1}}])])};
assert.equal(defEq(env,[],many(C("Except.bind"),[C("String"),natType,natType,exceptOkOne,exceptAddOne]),many(C("Except.ok"),[C("String"),natType,{tag:"lit",literal:{tag:"nat",value:2}}])),true);
assert.equal(defEq(env,[],many(C("Except.bind"),[C("String"),natType,natType,exceptError,exceptAddOne]),exceptError),true);
const oneWh=kernelWhnf(env,many(add,[zero,A(succ,zero)]));
assert.equal(oneWh.tag,"app");
if(oneWh.tag==="app"){assert.equal(pretty(oneWh.fn),"Nat.succ");assert.equal(pretty(kernelWhnf(env,oneWh.arg)),"Nat.zero");}

// Prove the first arithmetic theorem using the checked bootstrap as an imported prelude.
const theoremSource=`theorem addZero(n: Nat):\n  Eq.{1}(Nat, Nat.add(n, Nat.zero), n) :=\n  Eq.refl.{1}(Nat, n);\n`;
const withPrelude=checkSource(theoremSource,{prelude:foundation.artifact});
assert.equal(withPrelude.summary.status,"accepted");
assert.ok(withPrelude.summary.declarations.some(d=>d.name==="addZero"));
assert.deepEqual(withPrelude.summary.assumptions,["Array.all","Array.any","Array.append","Array.countP","Array.drop","Array.dropWhile","Array.filter","Array.find?","Array.foldl","Array.get?","Array.head?","Array.isEmpty","Array.last?","Array.map","Array.range","Array.replicate","Array.reverse","Array.size","Array.tail?","Array.take","Array.takeWhile","Array.toList","Except.bind","Except.map","Int.add","Int.beq","Int.neg","Int.sub","List.all","List.any","List.append","List.countP","List.drop","List.dropWhile","List.filter","List.find?","List.foldl","List.get?","List.head?","List.isEmpty","List.last?","List.length","List.map","List.range","List.replicate","List.reverse","List.tail?","List.take","List.takeWhile","List.toArray","Option.bind","Option.map"]);
console.log("✓ K1d Eq/Nat/Bool/Int/String/Option/List/Array/Except bootstrap plus bounded Int, List.map, List.foldl, Array, Array.map, Array.foldl, Option.isSome/Option.isNone/Option.getD/Option.orElse/Option.fold/Option.any/Option.toList/Option.toArray/Option.filter/Option.flatten/Option.bind, Except.isOk/Except.isError/Except.getD/Except.orElse/Except.toOption/Except.toError/Except.getErrorD/Except.swap/Except.fold/Except.bimap/Except.toList/Option.toExcept/Except.toArray/Except.mapError/Except.flatten/Except.bind, List.filter/List.append/List.length/List.range/List.replicate/List.singleton/List.toArray/List.isEmpty/List.reverse/List.any/List.all/List.find?/List.countP/List.head?/List.get?/List.take/List.takeWhile/List.dropWhile/List.drop/List.last?/List.tail?, and Array.filter/Array.append/Array.range/Array.replicate/Array.singleton/Array.toList/Array.isEmpty/Array.reverse/Array.any/Array.all/Array.find?/Array.countP/Array.head?/Array.take/Array.takeWhile/Array.dropWhile/Array.drop/Array.last?/Array.tail? primitive reductions, transparent def, delta reduction, and addZero theorem passed");
