import fs from "node:fs";
import path from "node:path";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const cli=path.join(root,"packages/cli/dist/cli.js");
const src=path.join(root,"tests/conformance/positive/k1d-prelude-user.ps");
const out=path.join(root,"artifacts/test-k1d-prelude.pscore.json");
fs.mkdirSync(path.dirname(out),{recursive:true});
const run=(args,expect=0)=>{const r=spawnSync(process.execPath,[cli,...args],{cwd:root,encoding:"utf8"});if(r.status!==expect)throw new Error(`${args.join(" ")} failed (${r.status})\n${r.stdout}\n${r.stderr}`);return r;};
const check=run(["check",src,"--std","--emit-core",out,"--json"]);
const summary=JSON.parse(check.stdout);
assert.equal(summary.status,"accepted");
assert.deepEqual(summary.declarations.map(d=>d.name),["Eq","Nat","Bool","Nat.add","addZeroFromPrelude"]);
const verify=JSON.parse(run(["verify",out,"--json"]).stdout);
assert.equal(verify.status,"accepted");
assert.equal(verify.declarations,5);
assert.equal(verify.projectPluginsLoaded,false);
const leanOut=path.join(root,"artifacts/test-k1d-prelude.lean");
run(["emit-lean",out,"--std","--out",leanOut]);
const lean=fs.readFileSync(leanOut,"utf8");
assert.ok(lean.includes("theorem addZeroFromPrelude"));
assert.ok(!/^inductive (Eq|Nat|Bool)/m.test(lean));
fs.rmSync(leanOut,{force:true});
fs.rmSync(out,{force:true});
console.log("✓ standard bootstrap prelude loads without redeclaration and isolated replay succeeds");
