import fs from "node:fs";
import path from "node:path";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");const cli=path.join(root,"packages/cli/dist/cli.js");
const out=path.join(root,"artifacts/test-k2h.pscore.json");const leanOut=path.join(root,"artifacts/test-k2h.lean");
const run=(args,expect=0)=>{const r=spawnSync(process.execPath,[cli,...args],{cwd:root,encoding:"utf8"});if(r.status!==expect)throw new Error(`${args.join(" ")} failed (${r.status})\n${r.stdout}\n${r.stderr}`);return r;};
fs.mkdirSync(path.dirname(out),{recursive:true});const summary=JSON.parse(run(["check","tests/conformance/positive/k2h-structure-update.ps","--std","--emit-core",out,"--json"]).stdout);assert.equal(summary.status,"accepted");
const artifact=JSON.parse(fs.readFileSync(out,"utf8"));assert.equal(artifact.formatVersion,12);assert.equal(artifact.implementationProfile,"K3c-section-vars0");
for(const n of ["updateLeft","updateBoth","updateLeftChanged","updateLeftPreservesRight","updateBothRight"])assert.ok(artifact.declarations.some(d=>d.name===n),`missing ${n}`);
const constants=(term,out=[])=>{if(!term||typeof term!=="object")return out;if(term.tag==="const")out.push(term.name);for(const k of ["fn","arg","domain","body","type","value"])if(term[k])constants(term[k],out);return out;};
const d=artifact.declarations.find(x=>x.name==="updateLeft");assert.ok(d&&d.kind==="definition");const cs=constants(d.value);assert.ok(cs.includes("PairNat.mk"));assert.ok(cs.includes("PairNat.right"),"unchanged field must be reconstructed through projection");assert.equal(JSON.stringify(d.value).includes("structUpdate"),false);
const replay=JSON.parse(run(["verify",out,"--json"]).stdout);assert.equal(replay.status,"accepted");assert.equal(replay.projectPluginsLoaded,false);
run(["emit-lean",out,"--std","--out",leanOut]);const lean=fs.readFileSync(leanOut,"utf8");assert.match(lean,/PairNat\.mk/);assert.match(lean,/PairNat\.right/);
for(const f of ["k2h-update-unknown-field.ps","k2h-update-duplicate-field.ps"])run(["check",`tests/conformance/negative/${f}`,"--std"],1);
run(["check","tests/conformance/negative/k2h-update-nonstructure-base.ps","--std"],2);
fs.rmSync(out,{force:true});fs.rmSync(leanOut,{force:true});
console.log("✓ K2h structure update lowers to constructor + projections, computes definitionally, rejects invalid updates, and independently replays");
