import fs from "node:fs";
import path from "node:path";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");const cli=path.join(root,"packages/cli/dist/cli.js");
const out=path.join(root,"artifacts/test-k2i.pscore.json");const leanOut=path.join(root,"artifacts/test-k2i.lean");
const run=(args,expect=0)=>{const r=spawnSync(process.execPath,[cli,...args],{cwd:root,encoding:"utf8"});if(r.status!==expect)throw new Error(`${args.join(" ")} failed (${r.status})\n${r.stdout}\n${r.stderr}`);return r;};
fs.mkdirSync(path.dirname(out),{recursive:true});
const summary=JSON.parse(run(["check","tests/conformance/positive/k2i-literals.ps","--std","--emit-core",out,"--json"]).stdout);assert.equal(summary.status,"accepted");
const artifact=JSON.parse(fs.readFileSync(out,"utf8"));assert.equal(artifact.formatVersion,12);assert.equal(artifact.implementationProfile,"K3c-section-vars0");
for(const n of ["zeroLit","threeLit","yesLit","noLit","succZeroLit","localLiteral","threeLiteralComputes","boolLiteralComputes"])assert.ok(artifact.declarations.some(d=>d.name===n),`missing ${n}`);
const serialized=JSON.stringify(artifact);assert.equal(serialized.includes('"tag":"natLit"'),false);assert.equal(serialized.includes('"tag":"boolLit"'),false);
const three=artifact.declarations.find(d=>d.name==="threeLit");assert.ok(three&&three.kind==="definition");const text=JSON.stringify(three.value);assert.ok(text.includes("Nat.succ")&&text.includes("Nat.zero"));
const replay=JSON.parse(run(["verify",out,"--json"]).stdout);assert.equal(replay.status,"accepted");assert.equal(replay.projectPluginsLoaded,false);
run(["emit-lean",out,"--std","--out",leanOut]);const lean=fs.readFileSync(leanOut,"utf8");assert.match(lean,/Nat\.succ/);assert.match(lean,/Bool\.true/);
for(const f of ["k2i-nat-literal-at-bool.ps","k2i-bool-literal-at-nat.ps","k2i-app-argument-mismatch.ps","k2i-large-nat-literal.ps"])run(["check",`tests/conformance/negative/${f}`,"--std"],2);
fs.rmSync(out,{force:true});fs.rmSync(leanOut,{force:true});
console.log("✓ K2i Nat/Bool literals lower to checked constructors, Pi-domain expected types drive application arguments, mismatched/oversized literals are unsupported, and isolated replay succeeds");
