import fs from "node:fs";
import path from "node:path";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");const cli=path.join(root,"packages/cli/dist/cli.js");
const out=path.join(root,"artifacts/test-k2j.pscore.json");const leanOut=path.join(root,"artifacts/test-k2j.lean");
const run=(args,expect=0)=>{const r=spawnSync(process.execPath,[cli,...args],{cwd:root,encoding:"utf8"});if(r.status!==expect)throw new Error(`${args.join(" ")} failed (${r.status})\n${r.stdout}\n${r.stderr}`);return r;};
fs.mkdirSync(path.dirname(out),{recursive:true});
const summary=JSON.parse(run(["check","tests/conformance/positive/k2j-equality.ps","--std","--emit-core",out,"--json"]).stdout);assert.equal(summary.status,"accepted");
const artifact=JSON.parse(fs.readFileSync(out,"utf8"));assert.equal(artifact.formatVersion,12);assert.equal(artifact.implementationProfile,"K3c-section-vars0");
for(const n of ["natReflSurface","boolReflSurface","proofReflSurface","equalityImplication","zeroRightSurface","addZeroSurface"])assert.ok(artifact.declarations.some(d=>d.name===n),`missing ${n}`);
const serialized=JSON.stringify(artifact);assert.equal(serialized.includes('"tag":"eq"'),false,"surface equality must disappear before core serialization");
const eqImp=artifact.declarations.find(d=>d.name==="equalityImplication");assert.ok(eqImp&&eqImp.kind==="theorem");assert.ok(JSON.stringify(eqImp.type).includes('"name":"Eq"'));
const replay=JSON.parse(run(["verify",out,"--json"]).stdout);assert.equal(replay.status,"accepted");assert.equal(replay.projectPluginsLoaded,false);
run(["emit-lean",out,"--std","--out",leanOut]);const lean=fs.readFileSync(leanOut,"utf8");assert.match(lean,/theorem equalityImplication/);assert.match(lean,/Eq\.\{1\}/);
run(["check","tests/conformance/negative/k2j-equality-type-mismatch.ps","--std"],1);
run(["check","tests/conformance/negative/k2j-boolean-equality-unsupported.ps","--std"],1);
run(["check","tests/conformance/negative/k2j-equality-without-foundation.ps"],2);
run(["check","tests/conformance/negative/k2j-chained-equality.ps","--std"],1);
fs.rmSync(out,{force:true});fs.rmSync(leanOut,{force:true});
console.log("✓ K2j propositional '=' lowers to checked Eq with inferred universe/type, binds tighter than implication, preserves '==' separation, and independently replays");
