import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';

const ROOT = path.resolve(import.meta.dirname, '..');
const node = process.execPath;
const psc = path.join(ROOT, 'bin', 'psc.mjs');
function run(cmd: string, args: string[], cwd = ROOT) {
  return spawnSync(cmd, args, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
}
function runOk(cmd: string, args: string[], cwd = ROOT) {
  const r = run(cmd, args, cwd);
  assert.equal(r.status, 0, `${cmd} ${args.join(' ')} failed\nstdout=${r.stdout}\nstderr=${r.stderr}`);
  return r;
}
function jsonFrom(r: ReturnType<typeof runOk>) {
  try { return JSON.parse(r.stdout); }
  catch { assert.fail(`expected JSON stdout, got:\n${r.stdout}\nstderr=${r.stderr}`); }
}
function sha256(file: string) { return createHash('sha256').update(fs.readFileSync(file)).digest('hex'); }

const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
assert.equal(pkg.name, 'proofscript');
assert.match(pkg.version, /^1\.0\.0-pskernel\.14[0-9]$/);
assert.equal(pkg.bin?.psc, './bin/psc.mjs');
assert.equal(pkg.scripts?.['test:ka137'], 'node --experimental-strip-types --disable-warning=ExperimentalWarning --disable-warning=MODULE_TYPELESS_PACKAGE_JSON tools/ka137-cli-language-workflow-tests.ts');

const version = runOk(node, [psc, '--version']);
assert.match(version.stdout, /^ProofScript 1\.0\.0-pskernel\.14[0-9]\b/);

const status = jsonFrom(runOk(node, [psc, 'language', 'status', '--json']));
assert.equal(status.status, 'accepted');
assert.equal(status.profile, 'ProofScript v0.7 alpha');
assert.ok(['implemented-alpha', 'usable-software-alpha'].includes(status.layers.programmingLanguage.status));
assert.equal(status.layers.theoremProver.status, 'partial-lean-export');
assert.ok(['structural-obligations', 'assert-ghost-old-alpha', 'usable-software-verification-alpha', 'lean-backed-obligation-alpha', 'verification-package-extraction-alpha', 'state-model-descriptor-alpha', 'monadic-lowering-skeleton-alpha', 'monadic-preflight-alpha'].includes(status.layers.formalVerification.status));
assert.ok(['structural-certificate-boundary', 'source-proof-runtime-certificate-alpha'].includes(status.layers.runtimeCorrespondence.status));
assert.ok(status.features.programming.includes('structures'));
assert.ok(status.features.formalVerification.includes('requires'));
assert.ok(status.commands.includes('emit-core'));
assert.ok(status.commands.includes('certify'));

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'proofscript-ka137-'));
const app = path.join(tmp, 'app');
jsonFrom(runOk(node, [psc, 'init', app, '--name', 'ka137-app', '--json']));

const coreFile = path.join(app, 'dist', 'Main.pscore.json');
const emitCore = jsonFrom(runOk(node, [psc, 'emit-core', 'src/Main.ps', '--out', coreFile, '--json'], app));
assert.equal(emitCore.status, 'accepted');
assert.equal(emitCore.command, 'emit-core');
assert.equal(emitCore.out, coreFile);
assert.equal(emitCore.trustBoundary.semanticPSKernelReplay, true);
assert.ok(fs.existsSync(coreFile));

const leanFile = path.join(app, 'dist', 'Main.lean');
const emitLean = jsonFrom(runOk(node, [psc, 'emit-lean', coreFile, '--out', leanFile, '--json'], app));
assert.equal(emitLean.status, 'accepted');
assert.equal(emitLean.command, 'emit-lean');
assert.equal(emitLean.out, leanFile);
assert.ok(fs.readFileSync(leanFile, 'utf8').includes('Generated by ProofScript'));

const certFile = path.join(app, 'dist', 'Main.pscert.json');
const certify = jsonFrom(runOk(node, [psc, 'certify', 'src/Main.ps', '--core', coreFile, '--out', certFile, '--json'], app));
assert.equal(certify.status, 'accepted');
assert.equal(certify.command, 'certify');
assert.equal(certify.certificate, certFile);
assert.ok(fs.existsSync(certFile));
const cert = JSON.parse(fs.readFileSync(certFile, 'utf8'));
assert.equal(cert.format, 'proofscript-certificate');
assert.ok([3, 4].includes(cert.version));
assert.equal(cert.core.sha256, sha256(coreFile));

const verifyCore = jsonFrom(runOk(node, [psc, 'verify', coreFile, '--json'], app));
assert.equal(verifyCore.status, 'accepted');
assert.equal(verifyCore.artifactKind, 'pscore');
assert.equal(verifyCore.sha256, sha256(coreFile));

const verifyCert = jsonFrom(runOk(node, [psc, 'verify', certFile, '--json'], app));
assert.equal(verifyCert.status, 'accepted');
assert.equal(verifyCert.artifactKind, 'certificate');
assert.equal(verifyCert.boundCoreSha256, sha256(coreFile));

const contractSrc = path.join(app, 'src', 'Contracts.ps');
fs.writeFileSync(contractSrc, `function boundedAdd(x: Nat, y: Nat, max: Nat): Nat\n  requires hx: x <= max\n  requires hy: y <= max\n  ensures upper: result <= x + y\n:= {\n  x + y\n}\n`);
const contractsFile = path.join(app, 'dist', 'Contracts.contracts.json');
const contractsLean = path.join(app, 'dist', 'Contracts.contracts.lean');
const contracts = jsonFrom(runOk(node, [psc, 'contracts', contractSrc, '--out', contractsFile, '--emit-lean', contractsLean, '--json'], app));
assert.equal(contracts.status, 'accepted');
assert.equal(contracts.obligations.length, 1);
assert.equal(contracts.trustBoundary.semanticProofChecking, false);

const obligations = jsonFrom(runOk(node, [psc, 'obligations', contractsFile, '--json'], app));
assert.equal(obligations.status, 'accepted');
assert.equal(obligations.count, 1);
assert.equal(obligations.obligations[0].status, 'unproved');
assert.equal(obligations.obligations[0].proofRequired, true);

const badContract = path.join(app, 'src', 'BadContract.ps');
fs.writeFileSync(badContract, `function f(x: Nat): Nat\n  invariant x = x\n  ensures upper: result = x\n:= {\n  x\n}\n`);
const bad = run(node, [psc, 'contracts', badContract, '--json'], app);
assert.equal(bad.status, 2, `bad contract must be unsupported\nstdout=${bad.stdout}\nstderr=${bad.stderr}`);
assert.equal(JSON.parse(bad.stdout).status, 'unsupported');

const packDir = path.join(tmp, 'pack');
fs.mkdirSync(packDir);
const pack = runOk('npm', ['pack', '--ignore-scripts', '--pack-destination', packDir]);
const tgzName = pack.stdout.trim().split(/\n/).find(line => line.endsWith('.tgz'));
assert.ok(tgzName);
const consumer = path.join(tmp, 'consumer');
fs.mkdirSync(consumer);
runOk('npm', ['init', '-y'], consumer);
runOk('npm', ['install', path.join(packDir, tgzName!), '--ignore-scripts', '--no-audit', '--no-fund'], consumer);
const installedStatus = jsonFrom(runOk('npx', ['psc', 'language', 'status', '--json'], consumer));
assert.equal(installedStatus.status, 'accepted');
assert.ok(installedStatus.commands.includes('emit-lean'));

console.log('KA137_CLI_LANGUAGE_WORKFLOW_TESTS=PASS');
