#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const repoRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const psc = path.join(repoRoot, 'bin', 'psc.mjs');
const example = path.join(repoRoot, 'examples', 'software-profile', 'src', 'BusinessRules.ps');

function run(args: string[], options: { cwd?: string } = {}) {
  return spawnSync(process.execPath, [psc, ...args], {
    cwd: options.cwd ?? repoRoot,
    encoding: 'utf8',
  });
}

assert.ok(fs.existsSync(psc), 'bin/psc.mjs must exist');
const packageJson = JSON.parse(fs.readFileSync(path.join(repoRoot, 'package.json'), 'utf8'));
assert.equal(packageJson.bin.psc, './bin/psc.mjs');
assert.equal(packageJson.bin.proofscript, './bin/psc.mjs');
assert.ok(!String(packageJson.scripts.build).includes('export NODE_OPTIONS'), 'build script must be PowerShell-compatible');

console.error('[psc adapter] help/status');
const help = run(['help']);
assert.equal(help.status, 0, help.stderr);
assert.match(help.stdout, /psc init/u);
assert.match(help.stdout, /psc compile/u);
assert.match(help.stdout, /psc build-ts/u);
assert.match(help.stdout, /psc setup/u);

const doctor = run(['doctor']);
assert.equal(doctor.status, 0, doctor.stderr);
assert.match(doctor.stdout, /powershellCompatibleScripts=yes/u);
assert.match(doctor.stdout, /requiresLean4=false/u);

const targets = run(['target', 'list']);
assert.equal(targets.status, 0, targets.stderr);
assert.match(targets.stdout, /software-ts\s+implemented/u);
assert.match(targets.stdout, /lean-full\s+future/u);

const language = run(['language', 'status']);
assert.equal(language.status, 0, language.stderr);
assert.match(language.stdout, /profile=proofscript-software-v0/u);
assert.match(language.stdout, /fullLean4Equivalence=false/u);

const status = run(['status', '--json']);
assert.equal(status.status, 0, status.stderr);
const statusJson = JSON.parse(status.stdout);
assert.equal(statusJson.requiresLean4, false);
assert.equal(statusJson.status, 'live-small-subset');

const checked = run(['check', example, '--json']);
assert.equal(checked.status, 0, checked.stderr);
assert.equal(JSON.parse(checked.stdout).status, 'accepted');

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'proofscript-psc-adapter-'));
try {
  const tsOut = path.join(tmp, 'BusinessRules.ts');
  const buildTs = run(['build-ts', example, '--out', tsOut, '--json']);
  assert.equal(buildTs.status, 0, buildTs.stderr + buildTs.stdout);
  assert.ok(fs.existsSync(tsOut));
  const builtText = fs.readFileSync(tsOut, 'utf8');
  assert.match(builtText, /Generated by ProofScript PSC-1 TypeScript backend/u);
  assert.equal(builtText.includes('from "./proofscript-runtime.js"') || builtText.includes("from './proofscript-runtime.js'"), true);
  assert.ok(fs.existsSync(path.join(tmp, 'proofscript-runtime.ts')), 'build-ts defaults to local runtime output');
} finally {
  fs.rmSync(tmp, { recursive: true, force: true });
}

console.log('PSC_CLI_ADAPTER0=PASS');
