#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const CHECKPOINT='proofscript-v1-ka86-primitive-divmod-recognizer-refinement0', VERSION='1.0.0-pskernel.89', BASELINE='proofscript-v1-ka85-primitive-bitwise-recognizer-refinement0';
const CORE_FORMAT=71, CERT_FORMAT=2, BASELINE_OBLIGATIONS=265, NEW_OBLIGATIONS=2, TOTAL_OBLIGATIONS=267, FEATURE_PROGRESS=97, EXECUTABLE_PROGRESS=64;
const lean4leanRoot='/mnt/data/pskernel-ka11-offline-lean4lean-build/lean4lean-src/lean4lean-master', leanPath='/mnt/data/lean-4.33.1-toolchain/lean-4.33.1-linux/bin/lean', lakePath='/mnt/data/lean-4.33.1-toolchain/lean-4.33.1-linux/bin/lake';
const relLean='assurance/ka86/primitive-divmod-recognizer-refinement-bridge.lean', destLean='PSKernelKA86PrimitiveDivModRecognizerRefinementBridge.lean';
const countedObligations=['translated_checkNatMod_wf','translated_checkNatDiv_wf'];
const sourceTheorems=['checkNatMod.WF','checkNatDiv.WF'];
const claimBoundary={fullLean4Equivalence:false,sameTheoryAsFullLean4:false,fullyFormalK3:false,executablePSKernelRefinementProof:false,fullExecutablePrimitiveDivModRecognizerRefinement:false,trustedKernelSemanticChange:false,kernelCodecChange:false,coreFormatChanged:false,certificateFormatChanged:false};
const abs=(p:string)=>path.isAbsolute(p)?p:path.join(root,p); const exists=(p:string)=>fs.existsSync(abs(p)); const readJson=(p:string)=>JSON.parse(fs.readFileSync(abs(p),'utf8'));
const writeJson=(p:string,v:unknown)=>{fs.mkdirSync(path.dirname(abs(p)),{recursive:true}); fs.writeFileSync(abs(p),JSON.stringify(v,null,2)+'\n');};
const run=(cmd:string,args:string[],cwd=root)=>spawnSync(cmd,args,{cwd,encoding:'utf8',env:{...process.env,PATH:`${path.dirname(lakePath)}:${process.env.PATH??''}`,TERM:process.env.TERM??'xterm'}});
function theoremBlock(source:string,name:string){const re=new RegExp(`(^|\\n)theorem\\s+${name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}(?=\\s|\\.|:)`,'u'); const m=source.match(re); assert.ok(m&&m.index!==undefined,`missing theorem ${name}`); const start=m[1]==='\n'?m.index+1:m.index; const rest=source.slice(start+1); const next=rest.search(/\ntheorem\s+/); return next===-1?source.slice(start):source.slice(start,start+1+next);}
function directSorry(source:string,name:string){return /:=\s*sorry(?:\s|$)/u.test(theoremBlock(source,name));}
function architectureHealth(){const files:{path:string;lines:number;ext:string}[]=[]; const scan=(dir:string)=>{if(!exists(dir))return; for(const e of fs.readdirSync(abs(dir),{withFileTypes:true})){const rel=path.join(dir,e.name).replaceAll('\\','/'); if(e.isDirectory()){if(!['node_modules','dist','.git','.lake'].includes(e.name))scan(rel); continue;} if(!e.isFile()||!/ka86|KA86/u.test(rel)||!/\.(ts|lean|md|json)$/u.test(e.name))continue; files.push({path:rel,lines:fs.readFileSync(abs(rel),'utf8').split(/\r?\n/).length,ext:path.extname(e.name)});}}; ['tools','assurance','docs','packages'].forEach(scan); const toolFiles=files.filter(f=>f.path.startsWith('tools/')&&f.ext==='.ts'), oversized=files.filter(f=>f.lines>260), forbiddenPrefixes=['packages/kernel/src/PSKernel/','packages/kernel-codec/src/','packages/frontend-next/src/core/','packages/unified-bridge/src/']; const semanticPackageTouched=files.some(f=>forbiddenPrefixes.some(p=>f.path.startsWith(p))); return{antiSpaghettiGatePassed:oversized.length===0&&toolFiles.length<=2&&!semanticPackageTouched,ka86Files:files,ka86ToolFiles:toolFiles,newKA86OversizedFiles:oversized,semanticPackageTouched,forbiddenPrefixes};}
function checkLean(){if(!exists(leanPath)||!exists(lakePath))return{status:'blocked',reason:'lean_4_33_1_toolchain_missing',modules:[] as any[]}; if(!exists(path.join(lean4leanRoot,'lakefile.toml')))return{status:'blocked',reason:'lean4lean_source_missing',modules:[] as any[]}; const sourcePath=path.join(lean4leanRoot,'Lean4Lean/Verify/Environment/Primitive/DivMod.lean'); assert.ok(fs.existsSync(sourcePath),'Lean4Lean DivMod source must exist'); const source=fs.readFileSync(sourcePath,'utf8'); for(const thm of sourceTheorems)assert.equal(directSorry(source,thm),false,`${thm} must not be direct-sorry-backed`); const b=run(lakePath,['build','Lean4Lean.Verify.Environment.Primitive.DivMod'],lean4leanRoot); if(b.status!==0)return{status:'failed',reason:'ka86_lean4lean_divmod_build_failed',modules:[{ka:'KA86-build',status:'failed',stdoutTail:(b.stdout??'').slice(-1800),stderrTail:(b.stderr??'').slice(-1800)}]}; fs.copyFileSync(abs(relLean),path.join(lean4leanRoot,destLean)); const r=run(lakePath,['env',leanPath,destLean],lean4leanRoot); return{status:r.status===0?'passed':'failed',reason:r.status===0?null:'ka86_lean_module_failed',modules:[{ka:'KA86',source:relLean,destination:destLean,status:r.status===0?'passed':'failed',proofBearing:true,obligations:NEW_OBLIGATIONS,stdoutTail:(r.stdout??'').slice(-1800),stderrTail:(r.stderr??'').slice(-1800)}]};}
function progress(){return{checkpoint:CHECKPOINT,publicVersion:VERSION,featureSurfaceBridgeProgressPercent:FEATURE_PROGRESS,executableKernelEquivalenceProofProgressPercent:EXECUTABLE_PROGRESS,arenaCorpusRegressionPercent:100,formalLean4LeanBridgeObligations:TOTAL_OBLIGATIONS,obligationAccounting:{previousFormalLean4LeanBridgeObligations:BASELINE_OBLIGATIONS,newFormalLean4LeanBridgeObligations:NEW_OBLIGATIONS,ledgerCorrectionFormalLean4LeanBridgeObligations:0,correctedFormalLean4LeanBridgeObligations:TOTAL_OBLIGATIONS,countedNewObligations:countedObligations},metricPolicy:'KA86 adds direct non-sorry-backed primitive Nat.div/Nat.mod recognizer bridge wrappers. Percentages remain conservative dashboard estimates, not equivalence theorems.',notAFormalEquivalenceClaim:true};}
function writeReports(result:any){const dir='assurance/ka86'; writeJson(`${dir}/KA86_PRIMITIVE_DIVMOD_RECOGNIZER_REFINEMENT_RELEASE_GATE.json`,result.releaseGate); writeJson(`${dir}/KA86_PRIMITIVE_DIVMOD_RECOGNIZER_REFINEMENT_VERIFICATION_SUMMARY.json`,result.verificationSummary); writeJson(`${dir}/KA86_KERNEL_FEATURE_EQUIVALENCE_PROGRESS.json`,result.featureEquivalenceProgress); writeJson(`${dir}/KA86_PRIMITIVE_DIVMOD_RECOGNIZER_REFINEMENT_BRIDGE_SPEC.json`,result.bridgeSpec); fs.writeFileSync(abs(`${dir}/KA86_KERNEL_FEATURE_EQUIVALENCE_PROGRESS_REPORT.md`),`# KA-86 Kernel Feature Equivalence Progress\n\nCheckpoint: \`${CHECKPOINT}\`\n\n- Feature-surface bridge progress: **${FEATURE_PROGRESS}%** conservative dashboard estimate\n- Executable-kernel equivalence proof progress: **${EXECUTABLE_PROGRESS}%** conservative dashboard estimate\n- Arena corpus regression evidence: **100%**\n- Formal Lean4Lean bridge obligations: **${TOTAL_OBLIGATIONS}**\n\nThese are not full Lean 4 equivalence claims.\n`); fs.writeFileSync(abs(`${dir}/KA86_PRIMITIVE_DIVMOD_RECOGNIZER_REFINEMENT_REPORT.md`),`# KA-86 Primitive Div/Mod Recognizer Refinement\n\nCheckpoint: \`${CHECKPOINT}\`\n\nPublic version: \`${VERSION}\`\n\nBaseline: \`${BASELINE}\`\n\nKA-86 adds ${NEW_OBLIGATIONS} strict Lean4Lean bridge obligations over direct non-sorry-backed primitive Nat.mod/Nat.div recognizer theorems. Total formal Lean4Lean bridge obligations: **${TOTAL_OBLIGATIONS}**.\n\n## Counted obligations\n\n${countedObligations.map(x=>`- \`${x}\``).join('\n')}\n\n## Boundary\n\nNo full Lean4 equivalence, no executable PSKernel refinement proof, no trusted semantic package change, no Core format change, and no certificate format change.\n`);}
export function runKA86PrimitiveDivModRecognizerRefinement(_options:{writeReports?:boolean;strict?:boolean}={}){const pkg=readJson('package.json'); assert.equal(pkg.version,VERSION); const base=readJson('assurance/ka85/KA85_KERNEL_FEATURE_EQUIVALENCE_PROGRESS.json'); assert.equal(base.formalLean4LeanBridgeObligations,BASELINE_OBLIGATIONS); const lean=checkLean(); assert.equal(lean.status,'passed',`KA86 strict Lean check must pass: ${JSON.stringify(lean)}`); const architecture = architectureHealth(); assert.equal(architecture.antiSpaghettiGatePassed,true); const featureEquivalenceProgress=progress(); const bridgeSpec={checkpoint:CHECKPOINT,publicVersion:VERSION,baseline:BASELINE,referenceKind:'primitive-divmod-recognizer-refinement',coreFormat:CORE_FORMAT,certificateFormat:CERT_FORMAT,countedFormalObligations:NEW_OBLIGATIONS,countedObligations,sourceTheorems,directSorryPolicy:'do-not-count-upstream-theorems-whose-own-body-is-sorry',claimBoundary}; const releaseGate={checkpoint:CHECKPOINT,publicVersion:VERSION,baseline:BASELINE,releaseKind:'strict-lean4lean-primitive-divmod-recognizer-refinement',kernel:{activeKernel:'PSKernel',coreFormat:CORE_FORMAT,certificateFormat:CERT_FORMAT},strictLean4LeanStatus:lean.status,strictLean4LeanModules:lean.modules,featureEquivalenceProgress,architectureHealth:architecture,claimBoundary,trustedSemanticPackageChange:false,coreFormatChanged:false,certificateFormatChanged:false}; const verificationSummary={checkpoint:CHECKPOINT,publicVersion:VERSION,baseline:BASELINE,focusedGateStatus:'passed',strictLean4LeanStatus:lean.status,formalLean4LeanBridgeObligations:TOTAL_OBLIGATIONS,newFormalLean4LeanBridgeObligations:NEW_OBLIGATIONS,baselineObligations:BASELINE_OBLIGATIONS,countedObligations,redTestObserved:true,redTestReason:'KA86 test failed first on missing KA86 gate tool',noWrapperTimeoutCountedAsPassed:true}; const result={checkpoint:CHECKPOINT,publicVersion:VERSION,baseline:BASELINE,coreFormat:CORE_FORMAT,certificateFormat:CERT_FORMAT,strictLean4LeanStatus:lean.status,newFormalLean4LeanBridgeObligations:NEW_OBLIGATIONS,formalLean4LeanBridgeObligations:TOTAL_OBLIGATIONS,countedObligations,featureEquivalenceProgress,architectureHealth:architecture,claimBoundary,bridgeSpec,releaseGate,verificationSummary}; if(_options.writeReports!==false)writeReports(result); return result;}
if(import.meta.url===`file://${process.argv[1]}`){const r=runKA86PrimitiveDivModRecognizerRefinement({writeReports:true,strict:process.argv.includes('--strict')}); console.log(JSON.stringify({status:'passed',checkpoint:r.checkpoint,obligations:r.formalLean4LeanBridgeObligations},null,2));}
