/-
PSKernel KA-7 generated real Lean4Lean import check template.

This file is copied or generated by tools/pskernel-ka7-real-import.ts into the
mounted Lean4Lean source tree and checked with that project's lake environment.
It intentionally imports real Lean4Lean modules rather than the KA-6
Lean4LeanCompat interface.
-/

import Lean4Lean
import Lean4Lean.Environment

#eval IO.println "PSKernel KA-7: real Lean4Lean import check reached Lean elaboration"
